var hi5=hi5||{};hi5.init={inited:false,funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(a){if(hi5.init.inited)return;hi5.browser.innerHeight=window.innerHeight;hi5.init.inited=true;var b=hi5.init.funcs;var d=0;for(var c=b.length;d<c;d++)b[d]();hi5.init.release()},release:function(){document.removeEventListener("DOMContentLoaded",hi5.init.start,false)}};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};
if(!Number.prototype.toByte)Number.prototype.toByte=function(){var a=this&255;return a>127?a-256:a};if(!Date.now)Date.now=function b(){return(new Date).getTime()};if(!String.prototype.applyArgs)String.prototype.applyArgs=function(a){var b=this.split("%");var d;var c;var f=b[0];var e=1;for(var g=b.length;e<g;e++){d=b[e];var h=parseInt(d,10);if(isNaN(h))f+=d;else{c=d.substring((h+"").length);d=a[h-1];if(d)f+=d;f+=c}}return f};
if(!String.prototype.hashCode)String.prototype.hashCode=function(){var a=0|0;var b=0;var d=this.length;for(var c=0;c<d;c++){b=this.charCodeAt(c);a=(a<<5)-a+b|0}return a};if(!Array.prototype.removeElm)Array.prototype.removeElm=function(a){var b=this.indexOf(a);if(b==-1)return;this.splice(b,1)};if(!Date.prototype.getStdTimezoneOffset)Date.prototype.getStdTimezoneOffset=function(){var a=new Date(this.getFullYear(),0,1);var b=new Date(this.getFullYear(),6,1);return Math.max(a.getTimezoneOffset(),b.getTimezoneOffset())};
if(!window.requestAnimationFrame)window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,30,Date.now())};window.URL=window.URL||window.webkitURL;
hi5.DateUtils={formatNum:function(a){return a<10?"0"+a:""+a},formatDate:function(a,b){if(!a)return"";var d=new Date(a);var c=d.getFullYear()+"-"+hi5.DateUtils.formatNum(d.getMonth()+1)+"-"+hi5.DateUtils.formatNum(d.getDate());if(b)c+=+" "+d.getHours()+":"+d.getMinutes();return c},parseDate:function(a){var b=a.split(" ");var d=b[0].split("-");if(d.length!=3)return null;if(b.length>1){var c=b[1].split(":");if(c.length!=2)return null;return new Date(d[0],d[1]-1,d[2],c[0],c[1])}else return new Date(d[0],
d[1]-1,d[2])}};hi5.NumUtils={toBytes:function(a,b){var d=a.toString(16);var c=d.length/2;var f=c|0;var e=0;if(!b)b=new Uint8Array(8);for(;e<f;e++)b[e]=parseInt(d.substr(-(e+1)*2,2),16);if(c>f)b[e]=parseInt(d[0],16);return b}};window.WebSocket=window.WebSocket||window.MozWebSocket;hi5.WebSocket=window.WebSocket;hi5.$=function(a){return document.getElementById(a)};
hi5.html={hasClass:function(a,b){return a.className.match(new RegExp("(\\s|^)"+b+"(\\s|$)"))},addClass:function(a,b){if(!hi5.html.hasClass(a,b))a.className+=" "+b},removeClass:function(a,b){if(hi5.html.hasClass(a,b)){var d=new RegExp("(\\s|^)"+b+"(\\s|$)");a.className=a.className.replace(d," ")}}};
hi5.browser=new function(){var a=navigator.userAgent;this.innerHeight=0;this.isEdge=a.indexOf("Edge")!=-1;var b=a.indexOf("MSIE")!=-1||a.indexOf("Trident")!=-1||this.isEdge;this.isIE=b;this.isTouch="ontouchstart"in window||"createTouch"in document||"DocumentTouch"in window&&window.document instanceof window.DocumentTouch||!!navigator.msMaxTouchPoints||navigator.maxTouchPoints>1||a.indexOf("Mobile")!=-1;this.isFirefox=a.indexOf("Firefox")!=-1&&!b;this.isOpera=a.indexOf("Opera")!=-1;this.isRIM=a.indexOf(" RIM ")!=
-1;this.isChrome=a.indexOf("Chrome")!=-1&&!b;this.isMacOS=a.indexOf("Mac OS")!=-1;this.isWindows=a.indexOf("Windows ")!=-1;this.isiOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?true:false;this.isSafari=a.indexOf("Chrome")==-1&&a.indexOf("Safari")!=-1&&!b;this.isWebKit=a.indexOf("WebKit")!=-1;this.isCrOS=a.indexOf("CrOS")!=-1;this.isOperaNext=a.indexOf("Edition Next")!=-1;this.isAndroid=a.indexOf("Android")!=-1;this.isChromeApp="chrome"in window&&"app"in chrome&&"window"in chrome.app;this.isDesktop=
!a.match(/(iPhone|iPod|iPad|Android|BlackBerry|Mobile)/);var d=window.outerHeight-window.innerHeight;this.isMetro=window.screenY==0&&(window.screenX==0||window.screenX+window.outerWidth==screen.width)&&d>3&&d<31;this.isMultitask=!(this.isiOS&&this.isSafari&&a.indexOf("Version/5")>0);this.binaryWS=function(){return hi5.browser.isChrome?true:hi5.tool.hasProperty(WebSocket,"binaryType")};this.cookie2Obj=function(){var a=document.cookie;var e={};var c;var b;if(a=="")return e;var d=a.split(";");var k=
0;for(var l=d.length;k<l;k++){for(var n=d[k];n.charAt(0)==" ";)n=n.substring(1,n.length);c=n.indexOf("=");if(c>0){b=decodeURIComponent(n.substring(c+1).replace(/\+/g," "));if(hi5.tool.isNumber(b)&&b[0]!="0"&&parseFloat(b)==b)b=parseFloat(b);if(b=="true"||b=="on")b=true;else if(b=="false"||b=="off")b=false;e[n.substring(0,c)]=b}}return e};this.getLibPath=function(a){var e=document.getElementsByTagName("script");var b;var c;var d="";var k=e.length;for(var l=0;l<k;l++){c=e[l].src;b=c.indexOf(a);if(b>
-1){d=c.substring(0,b);break}}return d};this.loadJS=function(a,e){if(a.indexOf("/")<0)a=hi5.libPath+a;if(hi5.browser.getLibPath(a))return;var b=document.createElement("script");b.type="text/javascript";b.src=a;if(e){b.onload=e;b.onreadystatechange=function(){if(this.readyState=="complete")e()}}var c=document.body||document.getElementsByTagName("script")[0].parentNode;c.appendChild(b)};this.formToObj=function(a,e){var b=a.elements;var c;var d;var k;var l;var n=b.length;if(!e)e={};for(var p=0;p<n;p++){c=
b[p];k=c.name;if(!k)continue;d=c.type;switch(d){case "submit":case "button":case "reset":continue;case "checkbox":l=c.checked;break;case "radio":if(!c.checked)continue;l=c.value;break;case "number":l=parseFloat(c.value);default:l=c.value}if(l=="")continue;e[k]=l}return e};this.objToForm=function(a,e){var b;var c;var d=e.elements;for(var k in a){b=d[k];if(!b)continue;c=a[k];var l=typeof c;if(l=="boolean")b.checked=c;else b.value=c}};this.objToCookie=function(a){for(var b in a){if(a[b]=="")continue;
document.cookie=b+"="+a[b]}};this.getScale=function(){return document.documentElement.clientWidth/window.innerWidth};this.httpGet=function(a,b){var c=new XMLHttpRequest;c.open("GET",a,b);c.setRequestHeader("Content-Type","text/plain;charset=UTF-8");c.send(null);return c.responseText};this.selectEditable=function(a){try{var b=document.createRange();b.selectNodeContents(a);var c=window.getSelection();c.removeAllRanges();c.addRange(b)}catch(d){console.log(d)}};this.setOrientaionHandler=function(a){if("onorientationchange"in
screen)screen.onorientationchange=a;else if("onmozorientationchange"in screen)screen.onmozorientationchange=a;else if("onmsorientationchange"in screen)screen.onmsorientationchange=a;else window.addEventListener("orientationchange",a,false)};var c={x:0,y:0};this.getMousePos=function(a,b){var d=(b||a.target).getBoundingClientRect();c.x=a.clientX-d.left;c.y=a.clientY-d.top;return c};this.calMousePos=function(a,b,d){var h=d.getBoundingClientRect();c.x=a-h.left*(d.width/h.width);c.y=b-h.top*(d.height/
h.height);if(hi5.browser.isTouch&&hi5.browser.isSafari){c.x-=document.body.scrollLeft;c.y-=document.body.scrollTop}return c};this.getHost=function(){var a=hi5.tool.queryToObj().gateway;if(!a&&!hi5.browser.isChromeApp){a=location.host;if(!a)a="localhost";else{var b=location.pathname;var c=b.indexOf("://");if(c>0)a+=b.substring(0,b.indexOf("/",c+3))}}return a};this.html2text=function(a){var b=document.createElement("div");b.innerHTML=a.replace(/<br>|<\/p>/gi,"\n</p>");return b.textContent.replace(/\r?\n/g,
"\r\n").replace(new RegExp("\u00a0","g")," ")};this.dataURLtoBlob=function(a){var b=a.indexOf(",");var c=a.substring(0,b++);var d=c.indexOf(":");var m=c.indexOf(";",d);var k=m>d?c.substring(d+1,m):"text/plain";var l=c.indexOf("base64",d)>0?hi5.Base64.dec(a,b,true):a.substring(b);return new Blob([l],{type:k})}};hi5.libPath=hi5.browser.getLibPath("hi5_min.js");if(!hi5.libPath)hi5.libPath=hi5.browser.getLibPath("hi5.js");
hi5.storage=new function(){function a(a,b){this._state=b||0;this._value=a}function b(a){if(a&&a.indexOf("{")==0){var b=JSON.parse(a);if(b&&"_state"in b&&"_value"in b)return b}return null}var d="chrome"in window&&!!chrome.storage;var c="localStorage"in window;if(c)try{localStorage.setItem("_t_s_t","1");localStorage.removeItem("_t_s_t")}catch(e){this.isAvailable=false;c=false}this.isAvailable=!!d||c;var f=d||!this.isAvailable?{}:localStorage;if(d)chrome.storage.local.get(null,function(a){for(var b in a)f[b]=
a[b]});this.set=function(b,c){f[b]=JSON.stringify(new a(c,1))};this.get=function(a){var c=f[a];var d=b(c);return d?d._value:c};this.clear=function(a){f={};if(d)chrome.storage.local.clear(a||function(){});else if(c)localStorage.clear()};this.remove=function(a){if(f.removeItem)f.removeItem(a);else{var c=b(f[a]);if(c){c._state=2;f[a]=JSON.stringify(c)}}};this.commit=function(a){a=a||function(){};if(d){var c={};var h=[];var m=false;for(var k in f){var l=b(f[k]);if(!l)continue;if(l._state==1){c[k]=l._value;
m=true}else if(l._state==2)h.push(k)}if(h.length>0){var n=function(){var b=0;for(var c=h.length;b<c;b++)delete f[h[b]];a&&a()};chrome.storage.local.remove(h,n)}if(m)chrome.storage.local.set(c,a)}else a()}};
hi5.Arrays={fill:function(a,b,d,c){if(a.fill)a.fill(c,b,d);else for(var f=b;f<d;f++)a[f]=c},arraycopy:function(a,b,d,c,f){if(d.set&&a.subarray)d.set(a.subarray(b,b+f),c);else for(var e=0;e<f;e++)d[c+e]=a[b+e]},equals:function(a,b){if(a==b)return true;if(!a||!b)return false;var d=a.length;if(d!=b.length)return false;for(var c=0;c<d;c++)if(a[c]!=b[c])return false;return true},startWidth:function(a,b){var d=0;for(var c=b.length;d<c;d++)if(a[d]!=b[d])return false;return true},__sortNumber:function(a,
b){return a-b},sortNumber:function(a){return a.sort(hi5.Arrays.__sortNumber)},hashCode:function(a){var b=1|0;var d=0;for(var c=a.length;d<c;d++)b=31*b+a[d]|0;return b},release:function(a){if(a){var b=0;for(var d=a.length;b<d;b++)a[b]=null;a=null}}};hi5.callback={callbacks:{},no:0,put:function(a){var b="CB"+this.no++;this.callbacks[b]=a;return b},get:function(a){var b=this.callbacks[a];if(b)delete this.callbacks[a];return b}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},cumulativePos:function(a){var b=0;var d=0;do{b+=a.offsetTop||0;d+=a.offsetLeft||0;b+=parseInt(a.style.borderLeftWidth)||0;d+=parseInt(a.style.borderTopWidth)||0;b-=a.scrollTop;d-=a.scrollLeft;a=a.offsetParent;if(a==document.body)break}while(a);return{x:d,y:b}},getPos:function(a,b){var d=0;var c=0;do{if(b&&getComputedStyle(a).getPropertyValue("position")!="static")break;d+=a.offsetLeft;c+=a.offsetTop}while(a=a.offsetParent);return{x:d,
y:c}},bytesToSize:function(a){if(isNaN(a))return"";var b=[" bytes"," KB"," MB"," GB"," TB"," PB"," EB"," ZB"," YB"];var d=Math.floor(Math.log(+a)/Math.log(2));if(d<1)d=0;var c=Math.floor(d/10);a=+a/Math.pow(2,10*c);if(a.toString().length>a.toFixed(3).toString().length)a=a.toFixed(2);return a+b[c]},queryToObj:function(a,b){if(!a)a=location.search.substring(1);var d=b||{};if(!!a){var c=a.split("&");var f=c.length;for(var e=0;e<f;e++){var g=c[e].split("=");d[g[0]]=decodeURIComponent(g[1])}}return d},
replaceQuery:function(a,b,d){var c=a.indexOf(b+"=");var f=false;if(c>0){var e=a.charAt(c-1);if(e=="&"||e=="?")f=true}if(!f)return a+="&"+b+"="+encodeURIComponent(d);var g=new RegExp("[\\?&]"+b+"=([^&#]*)");return a.replace(g,function(a){return a.charAt(0)+b+"="+encodeURIComponent(d)})},disableInput:function(){var a=document.createElement("div");a.style.position="fixed";a.style.left=0;a.style.top=0;a.style.width="100%";a.style.height="100%";a.style.zIndex=99999;a.style.background="url("+hi5.libPath+
"spinner.gif) no-repeat center center";document.body.appendChild(a);window.__hi5_bk=a},enableInput:function(){if(window.__hi5_bk){document.body.removeChild(window.__hi5_bk);window.__hi5_bk=null}},scale:function(a,b,d,c,f){var e=c===undefined?"left top":c+" "+f;if(!d)d=b;a.style.transformOrigin=e;a.style.MozTransformOrigin=e;a.style.webkitTransformOrigin=e;a.style.msTransformOrigin=e;a.style.OTransformOrigin=e;b="scale("+b+","+d+")";a.style.transform=b;a.style.MozTransform=b;a.style.webkitTransform=
b;a.style.msTransform=b;a.style.OTransform=b},openWebSocket:function(a,b,d){var c=false;if(d){var f=hi5.callback.put(d);a+="&callback="+f}var e=new WebSocket(a,"ctrl");e.onopen=function(a){c=true;if(b)e.send(b)};e.onclose=function(a){if(!c)alert("Failed to connect")};e.onmessage=function(a){var b=JSON.parse(a.data);e.close();if(b.callback)hi5.callback.get(b.callback)(b);else console.log(b)};return e},getChildNodesByTag:function(a,b){var d=a.childNodes;var c=[];var f=0;for(var e=d.length;f<e;f++){if(d[f].nodeName.toLowerCase()!=
b)continue;c.push(d[f])}return c},hasProperty:function(a,b){var d=b in a||b in a.prototype;if(d)return true;var c=a.__proto__||a.constructor.prototype;return b in c},isCapslock:function(a){var b=String.fromCharCode(a.keyCode||a.which);if(b.toUpperCase()==b&&b.toLowerCase()!=b&&!a.shiftKey)return true;return false},getImage:function(a,b){if(b&&b.indexOf("/")!=0)b=hi5.libPath+b;return hi5&&hi5.appcfg&&hi5.appcfg.img?hi5.appcfg.img[a]||b:b},uuid:function(){var a="";var b=new Array(16);var d="";for(var c=
0;c<16;c++){b[c]=Math.random()*255|0;d=b[c].toString(16);if(d.length==1)d="0"+d;switch(c){case 3:case 5:case 7:case 9:a+=d;a+="-";break;case 6:a+="4"+d[1];break;case 8:a+=(parseInt(d[0],16)&3|8).toString(16)+d[1];break;default:a+=d}}return a},text2html:function(a){return a.replace(/\n/g,"<br>")},Profiler:function(){function a(){this.count=0;this.totalTime=0}var b={};var d=0;var c=null;var f=false;this.begin=function(e){if(f){c=e;var h=b[e];if(h===undefined){h=new a;b[e]=h}d=(new Date).getTime();return h}};
this.end=function(a){if(f){var e=b[a||c];var m=(new Date).getTime()-d;e.totalTime=e.totalTime+m;e.count++;return e}};var e=function(){b={};d=0;c=null};this.start=function(){if(!f){f=true;e()}};this.stop=function(){if(f)f=false};this.isStarted=function(){return f};this.print=function(){console.log(this.getResult())};this.getResult=function(a){var c={};var d=typeof a==="undefined"?0:a.length;for(var e in b){if(d>0)if(e.substring(0,d)!==a)continue;c[e]=b[e]}return c}},ResponseMonitor:function(a,b){function d(){if(b)b()}
function c(){if(e){a();if(g)f=setTimeout(b,g)}}var f=0;var e=0;var g;this.tag=0;this.check=function(a){if(e){clearTimeout(f);f=setTimeout(c,a||e)}};this.setInterval=function(a,b){e=a*1E3|0;g=b*1E3|0};this.stop=function(){clearTimeout(f);e=0}}};
hi5.string={seperatedStr:{indexOf:function(a,b,d){var c=0;var f=a.indexOf(b,c);len=b.length,total=a.length;d=d||",";if(f==-1)return-1;if(f==0&&(len==a.length||a.charAt(len)==d))return 0;for(;a.charAt(f-1)!=d||a.charAt(f+len)!=d&&f+len!=total;){c=f+1;f=a.indexOf(b,c);if(f==-1)return-1}return f}}};navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;
hi5.audio={recordable:!!navigator.getUserMedia,getAudioContext:function(){var a=window;var b=window.AudioContext||window.webkitAudioContext;if(!b)return null;try{if(window.parent!=window)_golbal=window.parent}catch(d){}if(a.__audioCtx&&a.__audioCtx.state&&a.__audioCtx.state!="running"){if(a.__audioCtx.close)a.__audioCtx.close();a.__audioCtx=null}if(!a.__audioCtx)a.__audioCtx=new b;a.__audioCtx.__refCount=!a.__audioCtx.__refCount?1:a.__audioCtx.__refCount+1;return a.__audioCtx},releaseAudioContext:function(){var a=
window;try{if(window.parent!=window)_golbal=window.parent}catch(b){}if(a.__audioCtx){if(a.__audioCtx.__refCount)a.__audioCtx.__refCount--;if(!a.__audioCtx.__refCount||a.__audioCtx.__refCount<1){if(a.__audioCtx.close)a.__audioCtx.close();a.__audioCtx=null}}}};if(hi5.audio.recordable)if(hi5.browser.isChrome&&"https:"!=document.location.protocol)hi5.audio.recordable=false;
hi5.EventControl=function(a){a.addEvent=function(b,d){if(!a[b]||!a[b]._evt_listeners){a[b]=function(){a.fireEvent(b,arguments)};a[b]._evt_listeners=[]}a[b]._evt_listeners.push(d)};a.removeEvent=function(b,d){if(!a[b]&&!a[b]._evt_listeners)return false;var c=a[b]._evt_listeners;var f=c.indexOf(d);if(f>-1){c.removeElm(f);return true}return false};a.fireEvent=function(b,d){if(!a[b]||!a[b]._evt_listeners)return;var c=a[b]._evt_listeners;if(!d)d=[];var f=0;for(var e=c.length;f<e;f++)c[f].apply(a,d)};return a};
hi5.ui=hi5.ui||{};hi5.ui.initAs=function(a,b){var d=a["data-h5-ui"];if(!d){a["data-h5-ui"]=b;return true}if(hi5.string.seperatedStr.indexOf(d,b)!=-1)return false;else{a["data-h5-ui"]=d+","+b;return true}};hi5.ui.clean=function(a){if(a["data-h5-ui"])a["data-h5-ui"]=""};hi5.ui.confirm=function(a){return hi5.browser.isChromeApp?true:confirm(a)};
hi5.chromeapp={convertLink:function(a){var b=0;for(var d=a.length;b<d;b++)a[b].onclick=function(a){var b=a.target.href;var d=b.lastIndexOf("/");if(d!=-1)b=b.substring(d+1);chrome.app.window.create(b,{left:window.screenLeft+20,top:window.screenTop+20,width:window.innerWidth,height:window.innerHeight});return false}}};
hi5.Draggable=function(a,b){function d(a){var c=a.touchs||a.changedTouches;if(c){if(c.length!=1){g.dragging=false;return}a=c[0]}else if(a.button!=0)return;g.pos=hi5.tool.getPos(b);g.x=a.pageX;g.y=a.pageY;g.dragging=true;g.moved=false}function c(a){if(a.touchs)a=a.touchs[0];else if(a.changedTouches)a=a.changedTouches[0];var c=g.pos.x+a.pageX-g.x;var d=g.pos.y+a.pageY-g.y;if(c<0)c=0;if(c>window.innerWidth-b.offsetWidth)c=window.innerWidth-b.offsetWidth;if(d<0)d=0;if(d>window.innerHeight-b.offsetHeight)d=
window.innerHeight-b.offsetHeight;b.style.left=c+"px";b.style.top=d+"px"}function f(a){if(!g.dragging)return;if(!g.moved)g.moved=true;c(a)}function e(a){if(!g.moved)return;g.dragging=false;g.moved=false}b=b||a;a.draggable=false;if(!hi5.ui.initAs(b,"Draggable"))return b;var g={pos:null,x:0,y:0,dragging:false,moved:false};var h=hi5.browser.isTouch;a.addEventListener(h?"touchstart":"mousedown",d,false);document.addEventListener(h?"touchmove":"mousemove",f,false);document.addEventListener(h?"touchend":
"mouseup",e,false);if(h)document.addEventListener("touchcancel",e,false);return a};
hi5.Fadable=function(a,b,d){function c(){if(document.activeElement==a||document.activeElement==a.activeObj)setTimeout(c,g);else a.style.display="none"}function f(b){if(a.style.display=="block")return;setTimeout(function(){if(a.beforeDisplay)a.beforeDisplay();a.style.display="block";if(!m)return;if(h!=null)clearTimeout(h);h=setTimeout(c,g)},88);return false}if(!hi5.ui.initAs(a,"Fadable"))return a;if(a.tabIndex<0)a.tabIndex=999;var e=d||document;var g=b||3E3;var h=null;var m=true;a.setFadable=function(b){m=
b;if(b){var c="mouseup";if(navigator.pointerEnabled)c="pointerup";else if(navigator.msPointerEnabled)c="MSPointerUp";else if(hi5.browser.isTouch)c="touchend";e.addEventListener(c,f,false);if(c="touchend")e.addEventListener("mouseup",f,false)}else a.style.display="block"};a.startFade=f;return a};hi5.cancelDefault=function(a){if(a.preventDefault)a.preventDefault();if(a.stopPropagation)a.stopPropagation();return false};
hi5.Toolbar=function(a,b,d){if(b){var c=a.querySelector("#svImgHandle");var f=c||document.createElement("img");if(!c){f.style.cursor="move";f.style.width="11px";f.src=d;f.id="svImgHandle";hi5.Draggable(f,a);a.appendChild(f)}}a.addButton=function(b,c,d){var e=document.createElement("img");e.src=b;if(hi5.browser.isTouch){if(!navigator.msMaxTouchPoints)e.addEventListener("touchend",c,false)}else e.addEventListener("click",c,false);e.className="h5-img-btn";a.appendChild(e);if(d)e.id=d;return e};a.getButton=
function(b){var c=a.getElementsByTagName("img");var d=c.length;for(var e=0;e<d;e++)if(c[e].id==b)return c[e];return null};a.removeButton=function(b){var c=a.getElementsByTagName("img");var d=c.length;for(var e=0;e<d;e++)if(c[e].id==b){a.removeChild(c[e]);break}};var e=a.getElementsByTagName("img");var g=e.length;for(var h=0;h<g;h++)e[h].className="h5-img-btn";return a};
hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var b=a.getElementsByTagName("div")[0];a.setProgress=function(d){var c=Math.floor(d/a.maxValue*100);if(c==a.progress)return;a.progress=c;b.style.width=c/100*a.offsetWidth+"px"};return a};
hi5.Lightbox=function(a,b,d){function c(){var b=f.clientWidth;var c=f.clientHeight;var d=a.offsetWidth;var e=a.offsetHeight;if(d>b*.96){d=b*.96;a.style.width=d+"px"}if(e>c*.96){e=c*.96;a.style.height=e+"px";a.style.width=a.offsetWidth+22+"px"}var l=(b-d)/2;var n=(c-e)/3;a.style.left=l+"px";a.style.top=n+"px"}var f=document.createElement("div");f.id="divBackground";f.style.position="fixed";f.style.left=0;f.style.top=0;f.style.width="100%";f.style.height="100%";f.style.zIndex=999;f.style.backgroundColor=
d?d:"#222";if(!b)b=.4;if(b<1)f.style.opacity=b;a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var e=document.createElement("img");e.width=25;e.height=25;e.src=hi5.tool.getImage("del","del.png");e.className="h5-img-btn";e.style.cursor="pointer";e.align="top";e.style.position="absolute";e.style.top=0;e.style.right=0;a.resize=c;a.show=function(){var b=document.body;b.appendChild(f);a.appendChild(e);a.style.display="block";a.style.visibility="visible";c();if(a.onopen)a.onopen(a)};
a.visible=function(){return a&&a.style.visibility=="visible"};a.dismiss=function(b){function c(){var b=document.body;b.removeChild(f);a.removeChild(e);a.style.display="none";a.style.visibility="hidden";if(a.onclose)a.onclose()}if(typeof b=="number")setTimeout(c,b);else c()};a.background=f;e.addEventListener("click",a.dismiss,false);return a};
hi5.DataTable=function(a){if(hi5.ui.initAs(a,"DataTable")){hi5.EventControl(a);var b=typeof a;if(b=="string")a=JSON.parse(a);var d=a.rows;var c=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(a){var b=0;for(var d=c.length;b<d;b++)if(c[b].name==a)return b;return-1};a.getValue=function(b){var c=d[a.rowNo][b];return!a.beforeGetValue?c:a.beforeGetValue(b,c)};a.setValue=function(b,c){if(a.beforeSetValue)c=a.beforeSetValue(b,c);d[a.rowNo][b]=c;a.fireEvent("onchange",
[b,a.rowNo,c])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+1)};a.last=function(){a.moveTo(d.length-1)};a.hasNext=function(){return a.rowNo<d.length-1};a.remove=function(b){if(!b)b=a.rowNo;var c=[b];a.fireEvent("beforeremove",c);d.splice(b,1);a.fireEvent("onremove",c)};a.perform=function(b){if(typeof a[b]=="function")a[b].apply(a);else a.fireEvent("onaction",[b])};a.getObject=function(){var b=new Object;var d=0;for(var g=c.length;d<g;d++)b[c[d].name]=a.getValue(d);return b};
a.find=function(a,b){var c=0;for(var h=d.length;c<h;c++)if(d[c][a]==b)return d[c];return null}}a.fireEvent("onopen");return a};
hi5.DataGrid=function(a){function b(b){var d=this.rowIndex;if(typeof d=="number"){d=d-a.tHead.rows.length;c=d;a.dataTable.moveTo(d)}if(a.onrowclick)a.onrowclick(b)}function d(){if(!a._rowTemp){var b=a.tBodies[0].rows[0];a._rowTemp=b.cloneNode(true)}return a._rowTemp}if(!hi5.ui.initAs(a,"DataGrid"))return a;if("TABLE"!=a.nodeName)throw"Not HTML Table";a.dataTable=null;a.onrowclick=null;var c=-1;a.getValue=function(b){var d=a.dataTable;d.moveTo(c);return d.getValue(d.getColNo(b))};a.fillData=function(f){var e=
f.rows;var g=f.cols;var h=a.tBodies[0];var m;var k;var l;var n;var p=d();var q=p.cells.length;var r;var t=h.cloneNode(false);var u;l=e.length;for(k=0;k<l;k++){r=p.cloneNode(true);u=r.cells;f.moveTo(k);for(m=0;m<q;m++)if(!u[m].innerHTML){n=f.getValue(m);if(a.beforeDisplayValue)n=a.beforeDisplayValue(m,n);u[m].innerHTML=n}c=k;r.addEventListener("click",b,false);if(a.beforeAppendRow)a.beforeAppendRow(r);t.appendChild(r)}a.removeChild(h);a.appendChild(t)};a.open=function(){function b(c){var d=a.tBodies[0];
var f=d.rows[c];if(f)d.removeChild(f)}if(!a.dataTable)return;a.fillData(a.dataTable);a.dataTable.addEvent("onremove",b)};return a};
hi5.Select=function(a,b,d){if(!hi5.ui.initAs(a,"Select"))return a;var c=a.parentNode;var f=document.createElement("div");f.style.padding="0";f.style.display="inline";c.insertBefore(f,a);var e=document.createElement("img");e.src=hi5.tool.getImage("select","select.png");e.height=a.offsetHeight;e.style.verticalAlign="-6px";f.appendChild(a);f.appendChild(e);var g=document.createElement("select");if(b){g.multiple=true;if(!d)d=","}var h=a.getAttribute("hi5_size");g.size=h?h:10;var m=a.getAttribute("hi5_list");
if(m){var k=m.split(";");var l=k.length;if(l>0){var n=g.options;for(var p=0;p<l;p++)n[p]=new Option(k[p])}}g.style.position="absolute";g.style.zIndex=99999;g.style.display="none";document.body.appendChild(g);a.show=function(){if(a.beforedropdown)a.beforedropdown(a);g.style.display="";g.focus()};a.hide=function(){g.style.display="none";a.focus()};e.onclick=function(){if(g.style.display=="none"){if(g.options.length==0){var b=a.getAttribute("onfetchlist");if(b)eval(b)}var c=hi5.tool.getPos(a,false);
g.style.left=c.x+"px";g.style.top=c.y+a.offsetHeight+"px";g.style.width=a.offsetWidth+e.width+3+"px";a.show()}else a.hide()};g.onchange=function(){if(!b){a.value=g.value;g.style.display="none"}else{var c=[];var e;var f=g.options;var h=0;for(var m=f.length;h<m;h++){e=f[h];if(e.selected)c.push(e.value)}a.value=c.join(d)}if(a.onchange)a.onchange()};a.options=g.options;return a};hi5.init.push(function(){var a=document.getElementsByClassName("Hi5Select");var b=a.length;for(var d=0;d<b;d++)new hi5.Select(a[d])});
hi5.Tab=function(a){function b(b){var c=e;if(e!=b){g[e].className="tab_back";h[e].className="tab_hide";e=b}g[b].className="tab_front";h[b].className="tab_show";g[b].focus();if(c!=b)a.fireEvent("ontabchange",[b,c])}function d(a){var c=g.indexOf(a.target);if(c==-1)return;b(c)}if(!hi5.ui.initAs(a,"Tab"))return a;hi5.EventControl(a);var c=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes;var f=c.length;var e=0;var g=new Array(0);var h=new Array(0);for(var m=0;m<f;m++){var k=
c[m];if(k.nodeName.toUpperCase()!="SPAN")continue;k.className="tab_back";k.onclick=d;k.onfocus=d;g[g.length]=k}var l=a.getElementsByClassName("tab_body")[0].childNodes;f=l.length;for(m=0;m<f;m++){var n=l[m];if(n.nodeName.toUpperCase()!="DIV")continue;h[h.length]=n;n.className="tab_hide"}b(e);a.setSelected=b;a.getSelected=function(){return e};return a};hi5.init.push(function(){var a=document.getElementsByClassName("tab_all");var b=a.length;for(var d=0;d<b;d++)new hi5.Tab(a[d])});hi5.graphic={};
hi5.graphic.Line=function(a,b,d,c){this.x1=a||0;this.y1=b||0;this.x2=d||0;this.y2=c||0};hi5.graphic.Line.prototype.set=function(a,b,d,c){this.x1=a;this.y1=b;this.x2=d;this.y2=c};hi5.graphic.Line.prototype.intersection=function(a,b,d,c){var f=this.x1;var e=this.y1;var g=this.x2;var h=this.y2;var m=(c-b)*(g-f)-(d-a)*(h-e);if(m==0)return null;var k=((d-a)*(e-b)-(c-b)*(f-a))/m;var l=((g-f)*(e-b)-(h-e)*(f-a))/m;if(k>=0&&k<=1&&l>=0&&l<=1)return{x:f+(k*(g-f)|0),y:e+(k*(h-e)|0)};return null};
hi5.graphic.Rectangle=function(a,b,d,c){this.x=a;this.y=b;this.width=d;this.height=c;var f=this;this.union=function(a,b,c,d){var k=f.width;var l=f.height;if((k|l)<0){f.x=a;f.y=b;f.width=c;f.height=d;return}var n=c;var p=d;if((n|p)<0)return;var q=f.x;var r=f.y;k+=q;l+=r;var t=a;var u=b;n+=t;p+=u;if(q>t)q=t;if(r>u)r=u;if(k<n)k=n;if(l<p)l=p;k-=q;l-=r;f.x=q;f.y=r;f.width=k;f.height=l};this.intersection=function(a,b,c,d,k){var l=f.x;var n=f.y;var p=l;p+=f.width;var q=n;q+=f.height;var r=a;r+=c;var t=b;
t+=d;if(l<a)l=a;if(n<b)n=b;if(p>r)p=r;if(q>t)q=t;p-=l;q-=n;if(k){k.x=l;k.y=n;k.width=p;k.height=q;return k}return new hi5.graphic.Rectangle(l,n,p,q)};this.isEmpty=function(){return f.width<=0||f.height<=0}};
hi5.notifications=new function(){function a(a){var f=new b(a);d.getElement().appendChild(f);if(a.select){var e=f.getElementsByClassName("hi5_notifer_msg")[0];if(e.nodeName=="TEXTAREA")e.select();else hi5.browser.selectEditable(e)}}function b(b){function f(a,b){var c=document.createElement("span");c.className=b;c.onclick=function(b){a.apply(e,[b])};return c}var e=document.createElement("div");e.className="hi5_notifer slideUp";e.title=b.title;e.message=b.msg;e.msgCount=1;var g=document.createElement("div");
g.className="hi5_notifer_title";var h=document.createElement("span");h.className="hi5_notifer_icon";g.appendChild(h);g.appendChild(document.createTextNode(e.title));e.appendChild(g);var m=document.createElement("div");var k=b.format=="text/plain";var l=k?document.createElement("textarea"):document.createElement("div");l.className="hi5_notifer_msg";l.style.width="100%";l.innerHTML=b.msg;m.appendChild(l);if(!d.disableCounter){var n=document.createElement("span");n.className="hi5_notifer_count";e.addCount=
function(a){a=a||1;e.msgCount+=a;n.innerHTML="("+e.msgCount+")"};if(b.count&&b.count>1)e.addCount(b.count-1);m.appendChild(n)}if(b.cbNo)m.appendChild(f(b.cbNo,"hi5_notifer_button_no"));if(b.cbYes)m.appendChild(f(b.cbYes,"hi5_notifer_button_yes"));e.appendChild(m);e.destroy=function(){if(e.parentNode){e.parentNode.removeChild(e);var f=d.notifyPool.shift();if(f)a(f);else if(d.onempty&&d.notifySize()==0)d.onempty();if(b.cbClose)b.cbClose()}};if(b.timeout){var p=setTimeout(function(){e.destroy()},b.timeout);
e.addEventListener("mouseover",function(){clearTimeout(p)},false)}if(!b.cbYes&&!b.cbNo)e.onclick=e.destroy;return e}this.notifyPool=[];this.disableCounter=false;this.getElement=function(){var a=hi5.$("hi5_notifer_all");if(!a){a=document.createElement("div");a.id="hi5_notifer_all";document.body.appendChild(a)}return a};var d=this;this.notify=function(b){var f=typeof b=="string"?{msg:b,title:"",count:1}:b;if(!f.title)f.title="";if(!f.count)f.count=1;if(d.onnotify&&d.onnotify(f))return;var e=hi5.tool.getChildNodesByTag(d.getElement(),
"div");var g=e.length;if(!d.disableCounter&&g>0){var h=e[g-1];if(h.title==f.title&&h.message==f.msg){h.addCount();return}}if(g<3)a(f);else{var m=d.notifyPool;if(!d.disableCounter&&m.length>0){var k=m[m.length-1];if(k.title==f.title&&k.msg==f.msg){k.count++;return}}m.push(f)}};this.notifySize=function(){return hi5.tool.getChildNodesByTag(d.getElement(),"div").length};this.clearAll=function(){d.notifyPool.length=0;for(var a=d.getElement();a.hasChildNodes();)a.removeChild(a.firstChild)}};
hi5.Base64={table:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split(""),enc:function(a,b,d){var c="";var f=this.table;if(!b)b=a.length;if(!d)d=0;var e=d;var g=d+b-2;for(var h=b%3;e<g;e+=3){c+=f[a[e]>>2];c+=f[((a[e]&3)<<4)+(a[e+1]>>4)];c+=f[((a[e+1]&15)<<2)+(a[e+2]>>6)];c+=f[a[e+2]&63]}if(h==2){e=d+b-2;c+=f[a[e]>>2];c+=f[((a[e]&3)<<4)+(a[e+1]>>4)];c+=f[(a[e+1]&15)<<2];c+="="}else if(h==1){e=d+b-1;c+=f[a[e]>>2];c+=f[(a[e]&3)<<4];c+="=="}return c},binaries:[-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,0,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1],dec:function(a,b,d){var c=this.binaries;var f;var e;var g;var h;var m;var k;var l=0;var n=0;var p=a.indexOf("=")-b;var q=a.length;if(p<0)p=q-b;e=(p>>
2)*3+Math.floor(p%4/1.5);f=d?new Uint8Array(e):new Array(e);f[0]=0;for(g=0,h=b;h<q;h++){m=c[a.charCodeAt(h)&127];k=a.charAt(h)=="=";if(m==-1){console.log("Illegal character '"+a.charCodeAt(h)+"'");continue}n=n<<6|m;l+=6;if(l>=8){l-=8;if(!k)f[g++]=n>>l&255;n&=(1<<l)-1}}return f}};
hi5.file={readAsArrayBuffer:function(a,b){var d=new FileReader;d.onloadend=function(a){b(new Uint8Array(a.target.result))};d.readAsArrayBuffer(a)},getEntries:function(a){var b=a.target&&(a.target.webkitEntries||a.target.entries||[]);if(!b.length){var d=a.dataTransfer&&a.dataTransfer.items;if(d){var c=0;for(var f;f=d[c];++c){if(f.kind!="file")continue;if(!f.webkitGetAsEntry&&!f.getAsEntry)break;var e=f.webkitGetAsEntry()||f.getAsEntry();if(!e)break;b.push(e)}}}return b},getFilesFromEntries:function(a,
b){function d(){e--;if(!e)b(g)}function c(a){return function(b){b.fullPath=a;g.push(b);d()}}function f(a){var b=a.length;e+=b;for(var k=0;k<b;k++){var g=a[k];if(g.isFile)g.file(c(g.fullPath),function(a){console.log(a);d()});else if(g.isDirectory){var n=g.createReader();n.readEntries(function(a){if(a.length)f(a);d()},function(){d()})}}}var e=0;var g=[];f(a)},DirectoryReader:function(a){function b(a){return Array.prototype.slice.call(a||[],0)}function d(a,c){var d=a.createReader();var f=[];var k=function(){d.readEntries(function(a){if(!a.length)c(f);
else{f=f.concat(b(a));k()}})};k()}function c(a){var b=0;for(var h=a.length;b<h;b++){var m=a[b];if(m.isFile){var k=function(a){return function(b){f.onfile(b,a)}};m.file(k(m.fullPath))}else if(m.isDirectory)d(m,function(a){c(a)})}}var f=this;this.start=function(){c(a)}}};
hi5.DataBuffer=function(a,b,d){if(!b)b=0;if(!d)d=a.length;this.size=d;var c=b;var f=b+d;var e=hi5.Arrays.arraycopy;var g=this;this.attach=function(b,d,e){if(a)a=null;a=b;c=d;g.size=e;f=d+e};this.reset=function(a){c=0;g.size=f=a};this.markEnd=function(a){f=a||g.getPosition()};this.getEnd=function(){return f};this.has=function(a){return f-c>=a};this.getByte=function(){return a[c++]};this.getBytes=function(b){var d;if(a.slice)d=a.slice(c,c+b);else if(a.buffer&&a.buffer.slice)d=new Uint8Array(a.buffer.slice(c,
c+b));else{d=!!Uint8Array?new Uint8Array(b):new Array(b);if(d.set&&a.subarray)d.set(a.subarray(c,c+b));else for(var e=0;e<b;e++)d[e]=a[c+e]}c+=b;return d};this.copyToByteArray=function(b,c,d,f){e(a,d,b,c,f)};this.getCapacity=function(){return a.length};this.getPosition=function(){return c};this.getLittleEndian16=function(){var b=a[c+1]<<8|a[c];c+=2;return b};this.getBigEndian16=function(){var b=a[c]<<8|a[c+1];c+=2;return b};this.getLittleEndian32=function(){var b=a[c+3]<<24|a[c+2]<<16|a[c+1]<<8|a[c];
c+=4;return b};this.getLittleEndian64=function(){var b=a[c+7]<<56|a[c+6]<<48|a[c+5]<<40|a[c+4]<<32|a[c+3]<<24|a[c+2]<<16|a[c+1]<<8|a[c];c+=8;return b};this.getBigEndian32=function(){var b=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];c+=4;return b};this.getUnicodeString=function(a,b){var c=Math.floor(a/2);var d="";for(var e=0;e<c;e++){var f=this.getLittleEndian16();if(b&&f==0){this.skipPosition((c-e-1)*2);break}d+=String.fromCharCode(f)}return d};this.getAscllString=function(b,d){var e="";var g=b||f;if(a.subarray&&
b&&d===false){var n=c;c+=g;return String.fromCharCode.apply(null,a.subarray(n,n+g))}for(var p=0;p<g;p++){var q=this.getByte();if(q==0){if(b)this.skipPosition(b-p-1);break}e+=String.fromCharCode(q)}return e};this.setAscllString=function(b){var d=0;for(var e=b.length;d<e;d++)a[c++]=b.charCodeAt(d)};this.setUnicodeString=function(a){var b=a.length;for(var c=0;c<b;c++)this.setLittleEndian16(a.charCodeAt(c))};this.skipPosition=function(a){c+=a};this.setPosition=function(a){c=a};this.getData=function(){return a};
this.setByte=function(b){a[c++]=b};this.setBytes=function(b,d,e){if(a.set)if(!d&&!e){a.set(b,c);c+=b.length;return}else if(b.subarray){a.set(b.subarray(d,e),c);c+=e-d;return}if(!e)e=b.length;if(!d)d=0;for(var f=d;f<e;f++)a[c++]=b[f]};this.setLittleEndian16=function(b){a[c++]=b&255;a[c++]=b>>8&255};this.setLittleEndian32=function(b){a[c++]=b&255;a[c++]=b>>8&255;a[c++]=b>>16&255;a[c++]=b>>24&255}};
hi5.Chat=function(a,b){function d(a,b,c){var d=document.createElement("span");d.className=b;d.innerHTML=a;c.appendChild(d);return d}function c(){var a=e.value;h.add(a,b);e.value="";if(h.onchat)h.onchat(a,b)}var f=hi5.$("chatHistory");var e=hi5.$("chatText");var g=hi5.$("chatSend");var h=this;this.add=function(c,e){var g=document.createElement("div");d((e||b)+":","chatFrom",g);d(c,"chatMsg",g);var h=new Date;d(h.getHours()+":"+h.getMinutes()+":"+h.getSeconds(),"chatTime",g);if(a.style.display!="block")a.style.display=
"block";f.appendChild(g);f.scrollTop=f.scrollHeight};e.addEventListener("keydown",function(a){if(a.keyCode==13)c()},false);g.addEventListener("click",c,false)};document.addEventListener("DOMContentLoaded",hi5.init.start,false);
