svGlobal.auth=new function(){var h=this;this.login=function(t){function v(c,f){window.__sparkUser=null;if(h.beforelogin)if(h.beforelogin(c))return;var d=new WebSocket(c.substring(0,c.indexOf("?"))+"?_METHOD=post","login");d.onclose=function(d){if(h.afterlogin)h.afterlogin(q);q=false};d.onopen=function(d){q=true};d.onmessage=function(e){var b=e.data;if(b.indexOf("00")==0)d.send("00"+c.substring(c.indexOf("?")+1));else{var a=JSON.parse(e.data);if(!a.error)d.send("A1"+navigator.userAgent);f(a);d.close()}}}
var q=false;var f=hi5.browser.cookie2Obj();if(f.svSession&&f.svEmail)t+="&svSession="+f.svSession+"&svEmail="+encodeURIComponent(f.svEmail);setTimeout(function(){v(t,svGlobal.onloggedin)},5);return false}};
function startExitingApp(h){function t(c){v.addSurface(c);v.startExitingApp(h)}var v=svManager.getInstance();window.svOnSurfaceReady=t;var q=window.open("rail.html");q.svOnSurfaceReady=t;var f=hi5.$(h);var c=f.parentNode;c.removeChild(f);c=c.parentNode;if(c.getElementsByTagName("input").length==0){c.dismiss();v.checkRemaining(2E3)}}function getLoginURL(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"}
window.addEventListener("load",function(h){function t(){h.preventDefault();if(svGlobal.auth.beforesubmit)svGlobal.auth.beforesubmit();var d=hi5.$("frmLogin").elements;var e=d["user"].value;var b=d["pwd"].value;var a=getLoginURL()+"user="+encodeURIComponent(e)+"&pwd="+encodeURIComponent(b);var c=d["sharedSecret"];if(c&&c.value)a+="&sharedSecret="+encodeURIComponent(c.value);return svGlobal.auth.login(a)}function v(){window.__sparkUser=null;var d=hi5.$("frmLogin");d.elements["pwd"].value="";d.style.display=
"block";hi5.$("frmConn").style.display="none";var e=svManager.getInstance();if(e&&e.running())e.close()}function q(){hi5.tool.enableInput()}function f(d){var e=d.target;e.onclick=null;setTimeout(function(){e.onclick=f},300);x(e.id)}function c(){function d(a){b.addSurface(a);if(b.running())b.startApp(e.exe,e.args,"");else b.run()}var e=window.__sparkUser.server;var b=svManager.getInstance();if(b==null){b=new svGlobal.Rdp2(e);b.sessionTimeout=9E5}window.svOnSurfaceReady=d;var a=window.open("rail.html");
a.svOnSurfaceReady=d}function x(d,e,b){var a=window.__sparkUser;var f=a.servers;var h=f.length;var k;var u;var r;a.server=null;window.sparkGateway=a.gateway;for(var n=0;n<h;n++){var g=f[n];if(d==g.id){g=connvertServer(g);g["gateway"]=a.gateway;g["session"]=a.session;g["account"]=a.account;a.server=g;r=g.server_bpp;k=0;u=0;g.width=k;g.height=u;if(!r)r=16;g.color=r;break}}if(!a.server){hi5.notifications.notify("Not a valid server");return}else console.log("connecting to:"+a.server.id);var p=hi5.$("touchpad");
if(p&&p.checked)a.server.touchpad=true;var l=hi5.$("keyboard");if(l){var m=parseInt(l.options[l.selectedIndex].value);if(m>0)a.server.keyboard=m}if(typeof e=="undefined"){l=hi5.$("sameWindow");e=l&&l.checked}var t=a.server.startProgram=="app";if(t&&hi5.browser.isMultitask&&!e)c();else if(!e)window.open("rdpdirect.html");else{var w=new Rdp2(a.server);hi5.$("login").style.display="none";w.addSurface(new svGlobal.LocalInterface);w.run();w.onclose=function(){if(b){window.__sparkUser=null;var a=hi5.$("frmLogin");
a.elements["pwd"].value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else{w.hide();hi5.$("login").style.display="block"}}}}svGlobal.auth.beforelogin=function(){hi5.tool.disableInput()};svGlobal.auth.afterlogin=function(d){if(!d){hi5.notifications.notify(__svi18n.errorCode.connection);v()}q()};svGlobal.onloggedin=function(d){q();if(d.error){hi5.notifications.notify(__svi18n.errorCode["S"+d.name]);return}hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";
if(d.isDomainUser===true){var e=hi5.$("settings");if(e)e.parentNode.removeChild(e)}for(var b=hi5.$("programs");b.hasChildNodes();)b.removeChild(b.firstChild);var a=d.servers;if(!d.accessNotInList){var c=hi5.$("anyconn");if(c)c.style.display="none"}window.__sparkUser={session:d.session,account:hi5.$("user").value,gateway:hi5.$("gateway").value,servers:a};var h=a.length;if(h<1)return;var k="";for(var u=0;u<h;u++){var r=a[u].server;var n=a[u].id;var g=a[u].displayName||n||r;var p=a[u].icon;if(!p)p="rdp32.png";
var l=document.createElement("div");l.className="icon";var m=document.createElement("img");m.src=p;m.id=n;m.alt=n;m.title=g;m.style.cursor="pointer";m.onclick=f;l.appendChild(m);l.appendChild(document.createElement("br"));l.appendChild(document.createTextNode(g));b.appendChild(l);if(hi5.appcfg.startup&&n===hi5.appcfg.startup.server)k=n}if(!k&&hi5.appcfg.startup){console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead");k=a[0].id}if(k)x(k,!hi5.appcfg.startup.newWindow,
true)};(function e(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=t;var b=hi5.$("anyconn");if(b)b.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)};b=document.querySelector('input[name="showlogin"]');if(b)b.onclick=v;var a=hi5.browser.cookie2Obj();var c=document.cookie.indexOf("__SV_TOKEN_A")!=-1;var f=hi5.tool.queryToObj();if(a.svEmail||a.user||c||f.autoLogin){var k=hi5.$("frmLogin").elements;k["user"].value=a.svEmail||a.user||"";k["pwd"].value=(a.svSession?"fake":a.pwd)||
"_";if(a.gateway)k["gateway"].value=a.gateway;var h=k["gateway"].value&&k["user"].value&&k["pwd"].value||a.autoLogin||c||f.autoLogin;if(h)setTimeout(t,30)}b=hi5.$("settings");var r=hi5.$("settingsDiv");if(b)b.onclick=function(){if(r){var a=new hi5.Lightbox(r);a.show();hi5.$("currPwd").focus()}};b=hi5.$("frmSettings");if(b)b.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b["newPwd1"].value!=b["newPwd2"].value){hi5.notifications.notify(__svi18n.errorCode.pwdmatch);return}var e=getLoginURL()+
"_METHOD=post&action=put";var c=new WebSocket(e,"login");c.onmessage=function(a){var e=a.data;if(e.indexOf("00")==0){c.send("00currPwd="+b["currPwd"].value+"&newPwd="+b["newPwd1"].value+"&user="+hi5.$("user").value);hi5.$("frmSettings").reset()}else{var f=JSON.parse(a.data);if(f.error)hi5.notifications.notify(__svi18n.errorCode["S"+f.name]);c.close()}};if(r.dismiss)r.dismiss();return false};var n=hi5.$("sameWindow");if(n&&(hi5.browser.isiOS||hi5.browser.isIE||hi5.browser.isChromeApp))n.checked=true;
var g=hi5.$("gateway");var p=g.value;if(!p)p=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host;if(p.length==0)p="localhost";g.value=p;var l=hi5.$("touchpadmode");if(hi5.browser.isTouch)l.style.display="";var m=hi5.$("user");if(m&&!m.value&&hi5.appcfg&&hi5.appcfg.domain)m.value=hi5.appcfg.domain+"\\";(function y(){var a=false;var b="";try{document.createElement("canvas").getContext("2d");a=true}catch(e){b="This browser does not support Canvas.\n\n"}var c=
!("WebSocket"in window)&&!("MozWebSocket"in window);var f=navigator.userAgent;var g=f.indexOf("Firefox")!=-1;if(c){b+="This browser doesn't support WebSocket.\n\n";if(g)b+="Please update to Firefox 6 or later.\n\n";else if(f.indexOf("Opera")!=-1)b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n";else if(f.indexOf("MSIE")!=-1)b+="Please install Google Chrome Frame.\n\n"}if(b.length>0)hi5.notifications.notify(b);var h=
!c&&a;return h})();var q=hi5.$("defPort");if(q&&hi5.appcfg.defaultPort)q.innerHTML=hi5.appcfg.defaultPort})()},false);
