var svManager={getInstance:function(){var q=window.$telnet;if(q&&q.running&&q.running())return q;return null}};function connvertServer(q){var u=new Object;u.id=q.id;u.server=q.id;u.displayName=q.displayName||q.id;var y=q.vnc;if(y)for(var fa in y)u[fa]=y[fa];return u}
svGlobal.TELNET=function(q,u,y){function fa(c,a){function e(a,c,d,e,g,k){var l=a+g;var f=c+k;var w=I;var v;var h;var m;var n;for(h=0;h<e;h++){m=w[f+h];n=w[c+h];for(v=0;v<d;v++)m[l+v]=n[a+v]}}function d(a,c,d,e,g,k){var l=a+g;var f=c+k;var v=I;var w;var h;var m;var n;for(h=e-1;h>=0;h--){m=v[f+h];n=v[c+h];for(w=0;w<d;w++)m[l+w]=n[a+w]}}function k(a,c,d,e,g,l){var f=a+g;var w=c+l;var v=I;var h;var m;var n;var p;for(h=d-1;h>=0;h--){n=f+h;p=a+h;for(m=0;m<e;m++)v[w+m][n]=v[c+m][p]}}function l(a,c,d,e,g,
k){var h=a+g;var f=c+k;var w=I;var v;var m;var n;var p;for(v=0;v<d;v++){n=h+v;p=a+v;for(m=0;m<e;m++)w[f+m][n]=w[c+m][p]}}var I=[];var g=null;var f=new hi5.graphic.Rectangle(0,0,0,0);var h="Uint8ClampedArray"in window;this.width=c;this.height=a;var m=false;var n=this;this.pause=function(a){m=a};this.release=function(){n=null;g=null;I=null};this.isPaused=function(){return m};this.setContext=function(a){if(a==g)return;if(!g&&a&&!a.createImageData(1,1).data.buffer)h=false;g=a};this.getContext=function(){return g};
this.resize=function(d,e){for(var g=0;g<e;g++)I[g]=new Uint32Array(d);n.width=c=d;n.height=a=e};n.resize(c,a);this.getBuffer=function(){return I};this.setRGB=function(a,c,d){I[c][a]=d|4278190080};this.getRGB=function(a,c){return I[c][a]};this.setRGBs=function(a,c,d,e,g,k,v){var h=k;var f=0;var w=0;var l=a+d;var m=c+e;var n=I;var p;for(var q=c;q<m;q++,h+=v){w=h;p=n[q];for(f=a;f<l;f++)p[f]=g[w++]}};this.moveArea=function(a,c,g,f,h,m){if(m>0)d(a,c,g,f,h,m);else if(m<0)e(a,c,g,f,h,m);else if(h>0)k(a,
c,g,f,h,m);else l(a,c,g,f,h,m)};this.getRGBs=function(a,c,d,e){var g=d*e;var f=_Uint32Array(g);f[0]=0;var h=I;var k=a+d;var v=c+e;var m=0;var w;for(var l=c;l<v;l++)for(w=a;w<k;w++)f[m++]=h[l][w];return f};this.repaint=function(d,e,f,w){if(!g)return;if(d<0){f+=d;d=0}if(e<0){w+=e;e=0}if(d+f>c)f=c-d;if(e+w>a)w=a-e;var k=g.createImageData(f,w);var v=k.data;var l=d+f;var m=e+w;var n=0;var p=I;if(h){var q=new Uint32Array(v.buffer);var t;for(var r=e;r<m;r++)for(t=d;t<l;t++)q[n++]=p[r][t]}else{var u;var x;
for(r=e;r<m;r++)for(t=d;t<l;t++){u=p[r][t];x=n<<2;v[x]=u&255;v[x+1]=u>>8&255;v[x+2]=u>>16&255;v[x+3]=255;n++}}g.putImageData(k,d,e);k=null};this.postPaint=function(a,c,d,e){if(f.width>0)f.union(a,c,d,e);else{f.x=a;f.y=c;f.width=d;f.height=e}};this.commitPaint=function(){if(f.width>0){this.repaint(f.x,f.y,f.width,f.height);f.width=0}};this.fillRect=function(a,c,d,e,f){var g=I;var w=a+d;var v=c+e;var h;for(var k=c;k<v;k++)for(h=a;h<w;h++)g[k][h]=f}}function Aa(c,a){if(M)M.resize(c,a);else M=new fa(c,
a);return M}function Ba(){var c=q.indexOf("://");var a=q.substring(c+3);c=a.indexOf("/");if(c>0)a=a.substring(0,c);return location.protocol+"//"+a}function Za(c){if(!sessionId)return"";return hi5.browser.httpGet(Ba()+"/CLIP?s="+sessionId+"&t="+(new Date).getTime(),false)}function $a(){this.ws=null;this.setJoinMode=k.setJoinMode;this.requestControl=k.requestControl;this.writeKeyComb=k.writeKeyComb;this.getAppMode=function(){return k.mode};this.send=function(a){if(a=="891")return;if(!D)return;this.ws.send(a)};
this.sendInput=function(a){k.writeRawInput(a);if(k.onactivity)k.onactivity(a)};var c=null;this.getAppInfo=function(){return k.sessionInfo.appInfo};this.onresize=function(a){var e=a.target.svSurface;if(!e)return;var d=e.getFreeSpace();var f=d.width;var g=d.height;if(hi5.browser.isTouch||hi5.browser.isOpera)return;if(D){var h=function(){ga(f,g);Ca(E,Y)};if(c){clearTimeout(c);c=null}c=setTimeout(h,200)}};this.onorientationchange=function(a){};this.getClipData=Za;this.onfocus=function(a){};this.fileCallback=
[];this.getShareFiles=function(a,c){if(loggedin){this.ws.send("3A5"+a);this.fileCallback.push(c)}};this.notifyFiles=function(a){var c=this.fileCallback;var d=0;for(var f=c.length;d<f;d++)c[d](a)};this.getFile=function(a){window.open(k.getFileUrl(a))};this.removeFile=function(a){if(uploadMgr)uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return Ba()+"/DOWNLOAD?s="+sessionId+"&f="+a};this.getGateway=function(){return q};this.reconnect=function(a,c,d){}}function ab(){}function ka(c){return c==
"on"||c=="true"}function bb(){return h.displayName||k.server}function cb(c){if(k.setTitle)document.title=c}function Da(c,a,e){this.need=c;this.handler=a;this.repeat=e||1}function db(c){var a=0;var e=0;var d=new Uint8Array(c);var f=this;var g=new Da(0,null,0);this.release=function(){g=null;d=null;f=null};this.getHandler=function(){return g};this.getData=function(){return d};this.getPosition=function(){return a};this.setPosition=function(c){a=c};this.getEnd=function(){return e};this.set=function(c,
f,g){d=c;a=f;e=g};this.handle=function(){g.handler(f,g)};this.setHandler=function(c){if(c&&c.need<1)svGlobal.logger.warn("need < 1");g=c;if(c&&e-a>=c.need)c.handler(f,c)};this.getByte=function(){return d[a++]};this.peekByte=function(){return d[a]};this.getBE32=function(){return d[a++]<<24|d[a++]<<16|d[a++]<<8|d[a++]};this.getBE16=function(){return d[a++]<<8|d[a++]};this.skip=function(c){a+=c};this.skipBack=function(c){a-=c};this.getBytes=function(c,e){if(!e){var f=a;a+=c;return d.subarray(f,a)}else for(var g=
0;g<c;g++)e[g]=d[a++]};this.copyToByteArray=function(a,c,e,g){hi5.Arrays.arraycopy(d,e,a,c,g)}}function eb(){if(D)return;Ea();if(la)n=la;else{var c=hi5.tool.replaceQuery(q,"pwd","x");var a=hi5.browser.binaryWS();if(a)c+="&binary=on";var e=window.opener;if(e){var d=null;try{d=e.__sparkUser}catch(g){}if(d){var f=d.account;var k=d.session;if(f)c+="&account="+f;if(k)c+="&session="+k}}var l=hi5.browser.isChrome&&hi5.browser.isDesktop;c+="&pasteCap="+(l?3:0);n=new WebSocket(c,"telnet");n.binaryType="arraybuffer"}ma.ws=
n;svGlobal.logger.info(q);n.onopen=fb;if(h["recording"]!=undefined&&h["recording"]=="on")gb(h);n.onmessage=function(a){var c=a.data;if(typeof c!="string"){var d=new Uint8Array(c);if(N!=null)N.add(new RecordingObj(d,0,c.byteLength));ba.set(d,0,c.byteLength);ba.handle()}else{var e=parseInt(c.substring(0,2),16);var g=c.substring(2);switch(e){case 26:hb(g);break;case 27:ib(g);break;case 56:jb(g);break;case 59:kb(g);break;case 61:lb(g);break;case 62:mb(g);break;default:svGlobal.logger.warn("@TODO:"+c+
"\n")}}};n.onclose=ha;n.onerror=nb;ga(u+x,y+x)}function gb(c){N=new RecordingManager;var a=c.server;var e={name:a,width:c.width,height:c.height,color:c.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0};N.setHeader(e)}function ib(c){if(G.drawLicense!=false){A.drawLicense(c);na(h.fontSize)}}function kb(c){}function lb(c){var a=JSON.parse(c);switch(a.type){case 0:h.fontSize=parseInt(a.fontSize);u=a.width;y=a.height;Ea();A.setAutoScale(true);ga(u+x,y+x);var e=a.server;if(e){k.server=a.server;
cb(bb())}Fa=a.length;if(k.onopened)k.onopened(a);break;case 1:var d=a.duration;if(k.onprogress)k.onprogress(d,Fa);break;case 2:if(a.status==2){ab();D=true}else{var g=a.status==0;M.pause(g);if(a.warn)k.showMessage(g?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed)}}}function mb(c){var a=parseInt(c.substring(0,1),16);var e;var d;var f=c.substring(1);var h=false;var l=k.sessionInfo.appInfo;switch(a){case 1:d=JSON.parse(f);if(k.onsessionjoin)h=k.onsessionjoin(d);if(h)break;k.showMessage(__svi18n.info.joinsession.applyArgs([d.numericId,
d.__ip,d.name]));break;case 2:d=JSON.parse(f);if(k.onsessionexit)h=k.onsessionexit(d);if(h)break;k.showMessage(__svi18n.info.exitsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 3:d=JSON.parse(f);if(l.joinMode!=d.mode){l.joinMode=d.mode;var m=hi5.$("joinSelect");if(m)m.value=d.mode}if(l.hasControl)return;A.setReadOnly(false);e=hi5.$("requestControl");if(e)e.disabled=true;if(k.ongivecontrol)h=k.ongivecontrol();if(h)break;k.showMessage(__svi18n.info.givecontrol);break;case 4:A.setReadOnly(true);
l.hasControl=false;e=hi5.$("requestControl");if(e)e.disabled=false;if(k.ontakebackcontrol)h=k.ontakebackcontrol();if(h)break;k.showMessage(__svi18n.info.nocontrol);break;case 5:var n=function(){k.refuseControl(d.numericId);this.destroy()};var p=function(){k.giveControl(d.numericId);this.destroy()};d=JSON.parse(f);if(k.onrequirecontrol)h=k.onrequirecontrol(d);if(h)break;var q=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]);hi5.notifications.notify({"title":q,"msg":__svi18n.info.recontrol,
"cbYes":p,"cbNo":n});break;case 6:A.setTouchRemoting(true);break;case 7:d=JSON.parse(f);if(d.cols&&d.rows){var r=t*d.cols+x*2;var u=g*d.rows+x*2;M=Aa(r,u);ga(r,u)}break;case 8:d=JSON.parse(f);if(k.onrequestcredential&&k.onrequestcredential(d))return;A.requestCredential(d);break;case 9:break;case 11:var y=function(){k.allowJoin(d.numericId,false);this.destroy()};var z=function(){k.allowJoin(d.numericId,true);this.destroy()};d=JSON.parse(f);if(k.onrequirejoin)h=k.onrequirejoin(d);if(h)break;q=__svi18n.info.title.applyArgs([d.name,
d.numericId,d.__ip]);hi5.notifications.notify({"title":q,"msg":__svi18n.info.reqjoin,"cbYes":z,"cbNo":y})}}function jb(c){var a=JSON.parse(c);var e=a;sessionId=a.session;e.server=k.server;var d=hi5.$("joinSelect");if(d)d.value=e.joinMode;d=hi5.$("requestControl");if(d)d.disabled=e.hasControl;var g=G.page&&G.page.joinssh||"jointelnet.html";g=location.protocol+"//"+location.host+"/"+g+"?id="+a.numericId;var f=a.webAddress;if(f&&f.length>0){var h=f.indexOf("://");var l=f.substring(h+3);h=l.indexOf("/");
if(h>0)l=l.substring(0,h);if(l.toLowerCase()!=location.host.toLowerCase())g+="&gateway="+l}e.joinLink=g;k.sessionInfo.appInfo=e;if(a.ver&&a.ver!=svGlobal.version)svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);if(k.onsessionstart)k.onsessionstart(k.sessionInfo)}function Ub(c){var a=__svi18n.errorCode[c];if(!a)a="error "+c;if(k.onerror)k.onerror({name:c,message:a});if(k.displayMsg)hi5.notifications.notify({"msg":a});if(svGlobal.log>0)console.error(a)}function hb(c){var a=JSON.parse(c);
if(!a.name){if(svGlobal.log>0)console.erro("No error code for message:"+c);return}svGlobal.logger.info("msg="+c);if(k.onerror)k.onerror(a);var e=__svi18n.errorCode["S"+a.name]||"";e+=a.message;k.showMessage(e)}function fb(c){svGlobal.logger.info("opened...");D=true;n.send("87"+navigator.userAgent);if(k.onopen)k.onopen()}function nb(c){svGlobal.logger.warn(c)}function ha(c){svGlobal.logger.warn("closed ...");if(R)R.style.display="none";D=false;oa=false;if(k&&k.onclose)k.onclose();try{if(N!=null){N.exit();
N=null}if(A)A.close();if(V&&V.visible()){V.dismiss();V=null}}catch(a){}if(ba){ba.release();ba=null}l=null;S=null;if(n){n.onopen=null;n.onmessage=null;n.onclose=null;n.onerror=null;n=null}ma=null;A=null;k=null;if(window&&window.$telnet)window.$telnet=null;if(N!=null){N.exit();N=null}}function ob(){C=h.fgColor||H[7];B=h.bgColor||H[0]}function na(c,a){if(!a)a=L;l.font=c+"px "+a;t=l.measureText("X").width;Y=parseInt(y/g);E=parseInt(u/t);pa(parseInt(y/g))}function pa(c,a){if(a)T=a;if(c){O=c;ia=(O-1)*g+
r}Ga=T==1&&O==Math.floor(y/g)}function ga(c,a){var e=c-x;var d=a-x;var f=Math.floor(d/g);var k=Math.floor(e/t);var m=null;if(D){var n=Math.min(k*t+x,E*t+x);var p=Math.min(f*g+x,Y*g+x);m=l.getImageData(0,0,n,p)}u=e;y=d;A.setSize(c,a);na(h.fontSize);qa();if(m)l.putImageData(m,0,0);Y=f;E=k;pa(Math.floor(y/g))}function pb(){m=p;f=r;if(h.fontSize<10)h.fontSize=10;if(h.fontSize<=12){g=h.fontSize+6;ea=2}else if(h.fontSize>=13&&h.fontSize<18){g=h.fontSize+8;ea=2}else if(h.fontSize>=19&&h.fontSize<25){g=h.fontSize+
12;ea=3}else if(h.fontSize>=25){g=h.fontSize+16;ea=4}na(h.fontSize);remotectrl.style.cursor="text"}function Ea(){if(!R){qa();pb();R=document.getElementById("cursorID");R.style.display="block";R.style.width=t+"px";R.style.height=g+"px";oa=true}}function qa(){l.fillStyle=B;l.fillRect(0,0,S.width,S.height);l.fillStyle=C}function Ha(c){var a="";if(qb(c))if(ra){a=F[c]||"";if(a!="")J=J+a;else J=J+String.fromCharCode(c)}else if(c>127&&c<256)J=J+F[c];else J=J+String.fromCharCode(c);else{if(J!="")Ia(J);rb(c)}}
function sb(c){var a=c.getByte();switch(a){case 255:Ha(a);break;case 254:case 253:case 252:case 251:var e=c.getByte();tb(a,e);break;case 250:e=c.getByte();ub(e,c);break;default:return}if(!Ja){Ja=true;vb()}}function vb(){n.send("D0")}function ub(c,a){switch(c){case 24:var e=a.getByte();sa(a);if(e!=1)break;wb();break;case 32:e=a.getByte();sa(a);if(e!=1)break;xb();break;default:sa(a)}}function sa(c){for(;!yb;){var a=c.getByte();if(a==255){a=c.getByte();if(a==240)break}}}function tb(c,a){if(c==253&&!ta(a))ca(252,
a,true);else if(c==251&&!ua(a))ca(254,a,true);else if(c==254)ca(252,a,false);else if(c==252)ca(254,a,false);else if(c==253){ca(251,a,false);if(a==31)Ca(E,Y);else if(a==12)zb()}else if(c==251)ca(253,a,false)}function ca(c,a,e){n.send("D5"+c+"\t"+a+"\t"+(e==true?1:0));if(c==251){if(ta(a))Ka[a-0]=true}else if(c==252){if(ta(a))Ka[a-0]=false}else if(c==253){if(ua(a))La[a-0]=true}else if(c==254)if(ua(a))La[a-0]=false}function zb(){n.send("D7")}function Ca(c,a){n.send("D9"+c+"\t"+a)}function wb(){n.send("DA")}
function xb(){n.send("DC")}function ta(c){return Ma(c)&&Ab[c-0]}function ua(c){return Ma(c)&&Bb[c-0]}function Vb(c){return cmd<=255&&cmd>=236}function Ma(c){return c<=39&&c>=0}function qb(c){return K==ja&&!va[c]}function P(){K=ja}function rb(c){switch(c){case 0:case 24:P();return false;case 26:P();return false;case 5:return false;case 7:return false;case 8:Cb();return false;case 9:Db();return false;case 13:Eb();return false;case 10:case 11:case 12:Fb();return false;case 15:return false;case 14:return false;
case 17:case 19:return false;case 27:U="";K=wa;return false;default:if(c>=128&&c<=159)return false}switch(K){case ja:return true;case wa:if(c=="\\")return false;else if(c>=32&&c<=47){U=U+String.fromCharCode(c);return false}else if(c>=32&&c<=126||c>=160){Gb(c);if(K==wa)P();return false}return true;case Na:if(c>=48&&c<=63){Q=Q+String.fromCharCode(c);return false}else if(c>=32&&c<=47){Q=Q+String.fromCharCode(c);return false}else if(c>=32&&c<=126||c>=160){Hb(c);P();return false}return true;case Oa:case Pa:case Qa:case Ib:if(c>=
48&&c<=63)return false;else if(c>=32&&c<=47)return false;else if(c>=32&&c<=126||c>=160){K=Ra;return false}return true;case Ra:if(c>=32&&c<=126||c>=160)return false;return true;case Sa:K=Ta;return false;case Ta:P();return false;default:K=ja;return false}}function Jb(c,a){pa(a,c)}function Gb(c){if(U==null)U="";switch(c){case 48:if(U=="(")ra=true;break;case 65:f=f-g;z();return;case 66:if(U=="(")ra=false;return;case "C":m+=t;z();return;case 68:if(U=="")Ua(1);z();return;case "E":return;case 72:m=p;f=f+
g;return;case "I":return;case "J":return;case "K":case "L":return;case 77:if(U=="")Va(1);return;case "N":return;case "O":return;case "P":P();K=Oa;return;case "V":return;case "W":return;case "X":return;case "Y":K=Sa;return;case "Z":return;case "<":return;case " ":return;case "c":P();return;case 91:Q="";P();K=Na;return;case 93:P();K=Pa;return;case "^":P();K=Qa;case "_":case "\\":case ">":case "=":case "8":case "7":case "(":}}function Hb(c){var a=null;if(Q==null)Q="";if(Q!="")a=Q.split(";");var e=0;
var d=0;switch(c){case 65:if(a!=null&&a.length>=1)e=parseInt(a[0]);else e=1;f=f-e*g;if(f<r)f=r;z();return;case 66:if(a!=null&&a.length>=1)e=parseInt(a[0]);else e=1;var h=f;f+=e*g;var k=(f-h)/g;k=k==0?1:k;Z("\n",k);z();return;case 67:if(a!=null&&a.length>=1)d=parseInt(a[0]);else d=1;m=m+d*t;z();return;case 68:if(a!=null&&a.length>=1)d=parseInt(a[0]);else d=1;m=m-d*t;if(m<p)m=p;z();return;case 69:if(a!=null&&a.length>=1)e=parseInt(a[0]);else e=1;h=f;f+=e*g;k=(f-h)/g;k=k==0?1:k;Z("\n",k);m=p;z();return;
case 70:if(a!=null&&a.length>=1)e=parseInt(a[0]);else e=1;f=f-e*g;if(f<r)f=r;m=p;z();return;case 72:case 102:if(a!=null){if(a.length>=1){e=parseInt(a[0]);e=e-1;h=f;f=r+e*g;k=(f-h)/g;k=k==0?1:k;Z("\n",k)}if(a.length>=2){d=parseInt(a[1])-1;m=p+d*t}return}else if(Q==""){m=p;f=r}return;case 73:if(a.length>=1)var n=parseInt(a[0]);else n=1;m=p+n*8*t;return;case 74:if(a!=null&&a.length>=1){var q=parseInt(a[0]);if(q==1)Kb();else if(q==2){qa();m=p;f=r}}else Lb();return;case 75:if(a!=null&&a.length>=1){q=parseInt(a[0]);
if(q==1)xa(p,m);else if(q==2)xa(p,u+x);z()}else xa(m,u+x);return;case 76:if(a!=null&&a.length>=1){e=parseInt(a[0]);Va(e);z()}break;case 77:if(a!=null&&a.length>=1){e=parseInt(a[0]);Ua(e);z()}break;case "S":break;case "T":break;case 80:if(a!=null&&a.length>=1)d=parseInt(a[0]);else d=1;var y=l.getImageData(m+d*t,f,u+x-m-d*t,g);l.fillStyle=B;l.fillRect(m,f,u+x-m,g);l.putImageData(y,m,f);l.fillStyle=C;z();break;case 88:if(a!=null&&a.length>=1)d=parseInt(a[0]);else d=1;l.fillStyle=B;l.fillRect(m,f,d*t,
g);l.fillStyle=C;break;case "c":break;case "g":break;case "i":break;case 109:Mb(a);break;case "n":break;case "q":break;case 114:if(a!=null&&a.length>=2)Jb(parseInt(a[0]),parseInt(a[1]));case "x":case "y":default:}}function Kb(){l.fillStyle=B;l.fillRect(p,r,E*t,f-chart_height-r);l.fillRect(p,f,f-p,chart_height);l.fillStyle=C}function xa(c,a){l.fillStyle=B;l.fillRect(c,f,a-c,g);l.fillStyle=C}function Mb(c){ya=false;if(c==null||c.length==0){l.font="normal "+h.fontSize+"px "+L;ob()}else{var a=c.length;
var e=0;for(var d=0;d<a;d++){e=c[d]*1;switch(e){case 0:l.font="normal "+h.fontSize+"px "+L;B=H[0];C=H[7];break;case 1:l.font="bold "+h.fontSize+"px "+L;break;case 4:ya=true;break;case 5:l.font="italic "+h.fontSize+"px "+L;break;case 7:l.font="normal "+h.fontSize+"px "+L;B=H[7];C=H[0];break;case 22:l.font="normal "+h.fontSize+"px "+L;B=H[0];C=H[7];break;case 24:ya=false;break;case 25:l.font="italic "+h.fontSize+"px "+L;break;case 27:l.font="normal "+h.fontSize+"px "+L;B=H[7];C=H[0];break;default:if(c[d]>=
30&&c[d]<=39)C=H[c[d]-30+1];else if(c[d]>=40&&c[d]<=49)B=H[c[d]-40+1]}}}}function Lb(){l.fillStyle=B;l.fillRect(m,f,E*t-m+p,Y*g-f+r);l.fillStyle=C}function Cb(){m=m-t;if(m<p)m=p;z()}function Db(){var c=(m-p)/t/Wa;c=c*1;c=parseInt(c)+1;m=c*Wa*t+p;if(m>=E*t){m=p;f+=g;Z("\n")}z()}function Va(c){var a=l.getImageData(p,r+(T-1)*g,E*t,(O-T-c+1)*g);l.fillStyle=B;l.fillRect(p,r+(T-1)*g,E*t,g*c);l.putImageData(a,p,r+(T+c-1)*g);l.fillStyle=C}function Ua(c){var a=l.getImageData(p,(T+c-1)*g+r,E*t,(O-T-c+1)*g);
l.fillStyle=B;l.fillRect(p,(O-c)*g+r,E*t,c*g);l.putImageData(a,p,(T-1)*g+r);l.fillStyle=C}function Eb(){m=p;if(f>r+(O-1)*g)f=r+(O-1)*g;z()}function Fb(){f+=g;Z("\n");z();Nb()}function Nb(){if(m>=E*t){m=p;f+=g;Z("\n")}if(f>ia){for(;f>ia;)f-=g;z();if(Ga){var c=S.height-(r+g);l.drawImage(S,0,r+g,S.width,c,0,r,S.width,c);l.fillStyle=B;l.fillRect(0,ia,S.width,g)}else{var a=l.getImageData(p,r+g,E*t,(O-1)*g);l.fillStyle=B;l.fillRect(p,r,E*t,O*g);l.putImageData(a,p,r)}l.fillStyle=C}}function Ia(c){var a=
c;var e=a.length;if(f+g>y)f=(Y-1)*g+r;l.fillStyle=B;l.fillRect(m,f,t*e,g);l.fillStyle=C;l.fillText(a,m,f+g-3*ea);m=m+l.measureText(a).width;Z(a);z();J=""}function Wb(c,a,e){var d=(a-r)/g;if(c==p)Ob[d]=e}function z(){R.style.top=f+"px";R.style.left=m+"px"}function Xb(c){if(!k.openLink)return false;var a=c;c=c.toLowerCase();var e=c.indexOf("http://")==0||c.indexOf("https://")==0||c.indexOf("ftp://")==0||c.indexOf("mailto:")==0||c.indexOf("tel:")==0||c.indexOf("callto:")==0;if(!e)if(c.indexOf("www.")==
0){e=true;c="http://"+c}else if(c.indexOf("ftp.")==0){e=true;c="ftp://"+c}if(e){if(c.indexOf("\r")>0||c.indexOf("\n")>0)return false;if(k.onurlredirection&&k.onurlredirection(e))return true;A.processLink(a);return true}return false}function Pb(c){if(!D)return;var a=c.getData("text/plain");if(a){a=a.replace(/\r\n/g,"\n");aa(0,a,3);return true}return false}function Qb(){if(!V)return;if(!da)return;if(V.visible())return;da.value=W;V.show();if(A)A.setIgnorePaste(false);setTimeout(function(){da.scrollTop=
da.scrollHeight;da.disabled=false},10)}function Z(c,a){if(V){if(a)for(var e=0;e<a;e++)W=W+c;else W=W+c;if(W.length>1E5)W=W.substring(4E4)}}function aa(c,a,e){n.send("8B"+e+"\t"+a)}if(sessionStorage)sessionStorage.clear();var da=document.getElementById("copytextarea");var V=da?new hi5.Lightbox(document.getElementById("copydialog")):null;var W="";this.displayMsg=true;this.reconnectTimes=0;this.openLink=true;this.setTitle=true;this.mode=0;var la=typeof q=="object"?q:null;var Xa=typeof q=="object"||q.indexOf("/PLAY?")>
0;if(Xa){this.mode=1;if(la)q="";q+="&touchpad=on"}else if(q.indexOf("/JOIN?")>0){this.mode=2;this.reconnectOnResize=false}var G=hi5.appcfg||{img:{},toolbar:{fadable:true}};this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:true,trueColor:true};var A=null;var D=false;var oa=false;var ya=false;var x=5;var N=null;window.$telnet=this;G.copyDialog=true;var ja=0;var wa=27;var Na=155;var Oa=144;var Pa=157;var Qa=158;var Ib=159;var Ra=160;var Sa=161;var Ta=162;var F=new Array;for(var X=0;X<
127;X++)F[X]=String.fromCharCode(X);F[106]="+";F[107]="+";F[108]="+";F[109]="+";F[110]="+";F[113]="_";F[116]="+";F[117]="+";F[118]="+";F[119]="+";F[120]="|";(function a(){var e={128:199,129:252,130:233,131:226,132:228,133:224,134:229,135:231,136:234,137:235,138:232,139:239,140:238,141:236,142:196,143:197,144:201,145:230,146:198,147:244,148:246,149:242,150:251,151:249,152:255,153:214,154:220,155:162,156:163,157:165,158:8359,159:402,160:225,161:237,162:243,163:250,164:241,165:209,166:170,167:186,168:191,
169:8976,170:172,171:189,172:188,173:161,174:171,175:187,176:9617,177:9618,178:9619,179:9474,180:9508,181:9569,182:9570,183:9558,184:9557,185:9571,186:9553,187:9559,188:9565,189:9564,190:9563,191:9488,192:9492,193:9524,194:9516,195:9500,196:9472,197:9532,198:9566,199:9567,200:9562,201:9556,202:9577,203:9574,204:9568,205:9552,206:9580,207:9575,208:9576,209:9572,210:9573,211:9561,212:9560,213:9554,214:9555,215:9579,216:9578,217:9496,218:9484,219:9608,220:9604,221:9612,222:9616,223:9600,224:945,225:223,
226:915,227:960,228:931,229:963,230:181,231:964,232:934,233:920,234:937,235:948,236:8734,237:966,238:949,239:8745,240:8801,241:177,242:8805,243:8804,244:8992,245:8993,246:247,247:8776,248:176,249:8729,250:183,251:8730,252:8319,253:178,254:9632,255:160};for(var d=128;d<256;d++)F[d]=String.fromCharCode(e[d])})();var Bb=[true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
false,false,false,false,false,false,false,false,false,false];var Ab=[true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false];var Ka=[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
false,false,false,false,false,false,false,false,false];var La=[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false];var va=new Array(256);var Ya=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,155,156,157,158,159];for(X=0;X<256;X++)va[X]=false;for(var za=0;za<Ya.length;za++)va[Ya[za]]=
true;var ba=new db(4194304);this.running=function(){return D};var k=this;var n=null;var h=hi5.tool.queryToObj(q.substring(q.indexOf("?")+1));if(!u)u=window.innerWidth;u-=x;h.width=u;q+="&width="+u;if(!y)y=window.innerHeight;y-=x;h.height=y;q+="&height="+y;if(!h.fontSize){h.fontSize=13;q+="&fontSize="+13}else h.fontSize=parseInt(h.fontSize,10);this.server=h["server"];this.port=h["port"]?parseInt(h["port"],10):23;var H=["black","red","green","yellow","blue","magenta","cyan","white","gray","violet"];
var M=Aa(u,y);var l=M.getContext();var S;var ma=new $a;if(G.displayMsg!=undefined)this.displayMsg=G.displayMsg;if(G.reconnectTimes!=undefined)this.reconnectTimes=G.reconnectTimes;if(G.openLink!=undefined)this.openLink=G.openLink;if(G.setTitle!=undefined)this.setTitle=G.setTitle;if(typeof G.useWSS=="boolean")q=(G.useWSS?"wss":"ws")+q.substring(q.indexOf("://"));this.getURL=function(){return q};this.setJoinMode=function(a){if(!D)return;n.send("8E1"+a)};this.refuseControl=function(a){if(!D)return;n.send("8E3"+
a)};this.giveControl=function(a){if(!D)return;n.send("8E4"+a)};this.requestControl=function(){if(!D)return;n.send("8E2")};this.play=function(){n.send("F3")};this.pause=function(){n.send("F2")};this.scan=function(a){n.send("F4"+(a?"1":"0"))};this.seek=function(a){if(A&&D){n.send("F4"+(a?"1":"0")+"\t"+(a/A.getScale()|0));M.pause(true)}};var Fa=0;this.run=function(){eb()};this.hide=function(){if(!A)return;if(document.getElementById("cursorID").style.display=="block")document.getElementById("cursorID").style.display=
"none";A.hide()};this.showMessage=function(a){if(!k.displayMsg||!a)return;hi5.notifications.notify({"msg":a})};this.close=function(){if(n&&D)try{n.send("85");n.close()}catch(a){}else ha()};if(!hi5.browser.isChromeApp)window.addEventListener("unload",ha,false);else chrome.runtime.onSuspend.addListener(ha);var Ja=false;var yb=false;var R=null;x=5;var p=x;var r=5;var m=0;var f=0;var L=h.fontName||"Courier New";if(L.indexOf(" ")>0)L='"'+L+'"';var C=h.fgColor||H[7];var B=h.bgColor||H[0];var K=0;var Wa=
8;var Q="";var U="";var t=0;var g=18;var ea=0;var J="";var ra=false;var Y=0;var E=0;var T=1;var O=24;var ia=0;var Ga=true;var Rb=new Da(1024,function e(d){for(var f=true;f;){b=d.getByte();if(b<0)break;if(b==255)sb(d);else Ha(b);if(d.getPosition()>=d.getEnd()){if(J!="")Ia(J);f=false}}});ba.setHandler(Rb);var Ob=new Array;this.addSurface=function(e){A=e;if(Xa)e.setPlayerMode();M.setContext(A.context);l=M.getContext();S=l.canvas;e.forceTextArea=true;e.setAutoScale(k.mode>0);e.setSize(u+x,y+x);e.setController(ma);
e.setFastCopy(ka(h["fastCopy"]));e.setTouchpad(ka(h["touchpad"]));e.setClipboard(ka(h["mapClipboard"]));e.run(99997,false);e.onclipdata=Pb};var Sb=new Uint8Array(6);Sb[0]=5;var Tb=new Uint8Array(8);Tb[0]=4;this.writeRawInput=function(e){if(!oa)return;var d=parseInt(e.substring(0,2),16);var f=e.substring(2).split("\t");var g=0;var h=false;switch(d){case 128:var k=f[2];if(k==2)Qb();return;case 129:return;case 130:return;case 131:return;case 132:if(f[0]==0){g=parseInt(f[1]);h=f[0]==0;aa(h,g,0)}else if(f[1]==
42)aa(0,42,2);else if(f[1]==29)aa(0,29,2);return;case 139:if(f[0]==0){g=parseInt(f[1]);h=f[0]==0;aa(h,g,1)}return;case 134:g=f[0].charCodeAt(0);if(g==47)aa(true,191,1);else aa(0,f[0],3);return}svGlobal.logger.warn("Unknowncode: "+f[1]+" type:"+d)}};
