var svManager={getInstance:function(){var g=window.$ssh;if(g&&g.running&&g.running())return g;return null}};function connvertServer(g){var u=new Object;u.id=g.id;u.server=g.id;u.displayName=g.displayName||g.id;var p=g.ssh;if(p){for(var P in p)u[P]=p[P];u.user=p.username||"";u.pwd=p.password||""}return u}
svGlobal.SSH=function(g,u,p,P){function wb(){F=e.fgColor||T[7];G=e.bgColor||T[0]}function Aa(a,c){function d(a,b,c,d,f,e){var h=a+f;var k=b+e;var q=x;var r;var g;var l;var m;for(g=0;g<d;g++){l=q[k+g];m=q[b+g];for(r=0;r<c;r++)l[h+r]=m[a+r]}}function b(a,b,c,d,f,e){var h=a+f;var k=b+e;var q=x;var r;var g;var l;var m;for(g=d-1;g>=0;g--){l=q[k+g];m=q[b+g];for(r=0;r<c;r++)l[h+r]=m[a+r]}}function f(a,b,c,d,e,r){var h=a+e;var k=b+r;var g=x;var q;var l;var m;var n;for(q=c-1;q>=0;q--){m=h+q;n=a+q;for(l=0;l<
d;l++)g[k+l][m]=g[b+l][n]}}function k(a,b,c,d,f,e){var q=a+f;var r=b+e;var h=x;var g;var l;var m;var n;for(g=0;g<c;g++){m=q+g;n=a+g;for(l=0;l<d;l++)h[r+l][m]=h[b+l][n]}}var x=[];var h=null;var e=new hi5.graphic.Rectangle(0,0,0,0);var g="Uint8ClampedArray"in window;this.width=a;this.height=c;var l=false;var m=this;this.pause=function(a){l=a};this.release=function(){m=null;h=null;x=null};this.isPaused=function(){return l};this.setContext=function(a){if(a==h)return;if(!h&&a&&!a.createImageData(1,1).data.buffer)g=
false;h=a};this.getContext=function(){return h};this.resize=function(b,d){for(var f=0;f<d;f++)x[f]=new Uint32Array(b);m.width=a=b;m.height=c=d};m.resize(a,c);this.getBuffer=function(){return x};this.setRGB=function(a,b,c){x[b][a]=c|4278190080};this.getRGB=function(a,b){return x[b][a]};this.setRGBs=function(a,b,c,d,f,g,e){var q=g;var h=0;var r=0;var k=a+c;var l=b+d;var m=x;var n;for(var u=b;u<l;u++,q+=e){r=q;n=m[u];for(h=a;h<k;h++)n[h]=f[r++]}};this.moveArea=function(a,c,h,g,e,x){if(x>0)b(a,c,h,g,
e,x);else if(x<0)d(a,c,h,g,e,x);else if(e>0)f(a,c,h,g,e,x);else k(a,c,h,g,e,x)};this.getRGBs=function(a,b,c,d){var f=c*d;var h=_Uint32Array(f);h[0]=0;var g=x;var e=a+c;var q=b+d;var r=0;var k;for(var l=b;l<q;l++)for(k=a;k<e;k++)h[r++]=g[l][k];return h};this.repaint=function(b,d,f,e){if(!h)return;if(b<0){f+=b;b=0}if(d<0){e+=d;d=0}if(b+f>a)f=a-b;if(d+e>c)e=c-d;var q=h.createImageData(f,e);var r=q.data;var k=b+f;var l=d+e;var m=0;var n=x;if(g){var u=new Uint32Array(r.buffer);var p;for(var t=d;t<l;t++)for(p=
b;p<k;p++)u[m++]=n[t][p]}else{var w;var v;for(t=d;t<l;t++)for(p=b;p<k;p++){w=n[t][p];v=m<<2;r[v]=w&255;r[v+1]=w>>8&255;r[v+2]=w>>16&255;r[v+3]=255;m++}}h.putImageData(q,b,d);q=null};this.postPaint=function(a,b,c,d){if(e.width>0)e.union(a,b,c,d);else{e.x=a;e.y=b;e.width=c;e.height=d}};this.commitPaint=function(){if(e.width>0){this.repaint(e.x,e.y,e.width,e.height);e.width=0}};this.fillRect=function(a,b,c,d,f){var e=x;var h=a+c;var g=b+d;var q;for(var r=b;r<g;r++)for(q=a;q<h;q++)e[r][q]=f}}function qa(a,
c){if(E)E.resize(a,c);else E=new Aa(a,c);return E}function ra(){var a=g.indexOf("://");var c=g.substring(a+3);a=c.indexOf("/");if(a>0)c=c.substring(0,a);return location.protocol+"//"+c}function Ba(a){if(!sessionId)return"";return hi5.browser.httpGet(ra()+"/CLIP?s="+sessionId+"&t="+(new Date).getTime(),false)}function ga(a,c){if(c)A=c;if(a){I=a;ba=(I-1)*k}sa=A==1&&I==Math.floor(p/k)}function ha(a,c){var d=a-B;var b=c-B;var q=Math.floor(b/k);var r=Math.floor(d/n);var g=null;if(y){var l=Math.min(r*n+
B,C*n+B);var m=Math.min(q*k+B,W*k+B);g=h.getImageData(0,0,l,m)}u=d;p=b;w.setSize(a,c);h.font=e.fontSize+"px Courier New";ta();if(g)h.putImageData(g,0,0);W=q;C=r;ga(Math.floor(p/k));if(f.onresolutionchange)f.onresolutionchange(u,p)}function Ca(){this.ws=null;this.setJoinMode=f.setJoinMode;this.requestControl=f.requestControl;this.writeKeyComb=f.writeKeyComb;this.getAppMode=function(){return f.mode};this.send=function(a){if(a=="891")return;if(!y)return;this.ws.send(a)};this.sendInput=function(a){f.writeRawInput(a);
if(f.onactivity)f.onactivity(a)};var a=null;this.getAppInfo=function(){return f.sessionInfo.appInfo};this.onresize=function(c){var d=c.target.svSurface;if(!d)return;var b=d.getFreeSpace();var f=b.width;var e=b.height;if(hi5.browser.isTouch||hi5.browser.isOpera)return;if(y){var g=function(){ha(f,e);Da(u,p)};if(a){clearTimeout(a);a=null}a=setTimeout(g,200)}};this.onorientationchange=function(a){};this.getClipData=Ba;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,d){if(loggedin){this.ws.send("3A5"+
a);this.fileCallback.push(d)}};this.notifyFiles=function(a){var d=this.fileCallback;var b=0;for(var f=d.length;b<f;b++)d[b](a)};this.getFile=function(a){window.open(f.getFileUrl(a))};this.removeFile=function(a){if(uploadMgr)uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return ra()+"/DOWNLOAD?s="+sessionId+"&f="+a};this.getGateway=function(){return g};this.reconnect=function(a,d,b){}}function ca(a){return a=="on"||a=="true"}function Ea(){return e.displayName||f.server}function Fa(a){if(f.setTitle)document.title=
a}function ua(a,c,d){this.need=a;this.handler=c;this.repeat=d||1}function Ga(a){var c=0;var d=0;var b=new Uint8Array(a);var f=this;var e=new ua(0,null,0);this.release=function(){e=null;b=null;f=null};this.getHandler=function(){return e};this.getData=function(){return b};this.getPosition=function(){return c};this.setPosition=function(a){c=a};this.getEnd=function(){return d};this.set=function(a,f,e){b=a;c=f;d=e};this.handle=function(){e.handler(f,e)};this.setHandler=function(a){if(a&&a.need<1)svGlobal.logger.warn("need < 1");
e=a;if(a&&d-c>=a.need)a.handler(f,a)};this.getByte=function(){return b[c++]};this.peekByte=function(){return b[c]};this.getBE32=function(){return b[c++]<<24|b[c++]<<16|b[c++]<<8|b[c++]};this.getBE16=function(){return b[c++]<<8|b[c++]};this.skip=function(a){c+=a};this.skipBack=function(a){c-=a};this.getBytes=function(a,d){if(!d){var f=c;c+=a;return b.subarray(f,c)}else for(var e=0;e<a;e++)d[e]=b[c++]};this.copyToByteArray=function(a,c,d,f){hi5.Arrays.arraycopy(b,d,a,c,f)}}function Ha(){if(y)return;
if(ia){l=ia;ja()}else{va();g+="&cols="+C+"&rows="+W;var a=g;var c=hi5.browser.binaryWS();if(c)a+="&binary=on";var d=window.opener;if(d){var b=null;try{b=d.__sparkUser}catch(h){}if(b){var q=b.account;var k=b.session;if(q)a+="&account="+q;if(k)a+="&session="+k}}var m=hi5.browser.isChrome&&hi5.browser.isDesktop;a+="&pasteCap="+(m?3:0);g=a;a=f.mode==0&&z.wsPost?g.substring(0,g.indexOf("?"))+"?_METHOD=post":g;l=new WebSocket(a,"ssh");l.binaryType="arraybuffer"}ka.ws=l;svGlobal.logger.info(g);l.onopen=
Ia;if(e["recording"]!=undefined&&e["recording"]=="on")Ja(e);l.onmessage=function(a){var b=a.data;if(typeof b!="string"){var c=new Uint8Array(b);if(J!=null)J.add(new RecordingObj(c,0,b.byteLength));Q.set(c,0,b.byteLength);Q.handle()}else{var d=parseInt(b.substring(0,2),16);var f=b.substring(2);switch(d){case 0:Ka();break;case 15:La(f);break;case 26:Ma(f);break;case 27:Na(f);break;case 56:Oa(f);break;case 59:Pa(f);break;case 61:Qa(f);break;case 62:Ra(f);break;case 91:Sa(f);break;case 93:Ta(f);break;
default:svGlobal.logger.warn("@TODO:"+b+"\n")}}};l.onclose=da;l.onerror=Ua}function Ka(){var a=g.substring(g.indexOf("?")+1);l.send("00"+a);l.send("87"+navigator.userAgent)}function Ja(a){J=new RecordingManager;var c=a.user.length>0?a.server+"_"+a.user:a.server;var d={name:c,width:a.width,height:a.height,color:a.fontSize,namesuffix:".sshv",filetag:"SSHV",duration:0};J.setHeader(d)}function Na(a){if(z.drawLicense!=false)w.drawLicense(a)}function La(a){if(f.onready)f.onready();if(f.onloggedin)f.onloggedin()}
function Pa(a){}function Qa(a){var c=JSON.parse(a);switch(c.type){case 0:e.fontSize=parseInt(c.fontSize);u=c.width;p=c.height;ja();w.setAutoScale(true);ha(u+B,p+B);var d=c.server;if(d){f.server=c.server;Fa(Ea())}wa=c.length;if(f.onopened)f.onopened(c);break;case 1:var b=c.duration;if(f.onprogress)f.onprogress(b,wa);break;case 2:if(c.status==2){Va();y=true}else{var g=c.status==0;E.pause(g);if(c.warn)f.showMessage(g?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed)}}}function Va(){}function Ta(a){t+=
k;m=0;U(__svi18n.info.password||a);X=true}function Sa(a){la=true;U(__svi18n.info.user||a);L=true}function Ra(a){var c=parseInt(a.substring(0,1),16);var d;var b;var e=a.substring(1);var g=false;var h=f.sessionInfo.appInfo;switch(c){case 1:b=JSON.parse(e);if(f.onsessionjoin)g=f.onsessionjoin(b);if(g)break;f.showMessage(__svi18n.info.joinsession.applyArgs([b.numericId,b.__ip,b.name]));break;case 2:b=JSON.parse(e);if(f.onsessionexit)g=f.onsessionexit(b);if(g)break;f.showMessage(__svi18n.info.exitsession.applyArgs([b.numericId,
b.__ip,b.name]));break;case 3:b=JSON.parse(e);if(h.joinMode!=b.mode){h.joinMode=b.mode;var k=hi5.$("joinSelect");if(k)k.value=b.mode}if(h.hasControl)return;w.setReadOnly(false);d=hi5.$("requestControl");if(d)d.disabled=true;if(f.ongivecontrol)g=f.ongivecontrol();if(g)break;f.showMessage(__svi18n.info.givecontrol);break;case 4:w.setReadOnly(true);h.hasControl=false;d=hi5.$("requestControl");if(d)d.disabled=false;if(f.ontakebackcontrol)g=f.ontakebackcontrol();if(g)break;f.showMessage(__svi18n.info.nocontrol);
break;case 5:var l=function(){f.refuseControl(b.numericId);this.destroy()};var m=function(){f.giveControl(b.numericId);this.destroy()};b=JSON.parse(e);if(f.onrequirecontrol)g=f.onrequirecontrol(b);if(g)break;var n=__svi18n.info.title.applyArgs([b.name,b.numericId,b.__ip]);hi5.notifications.notify({"title":n,"msg":__svi18n.info.recontrol,"cbYes":m,"cbNo":l});break;case 6:w.setTouchRemoting(true);break;case 7:b=JSON.parse(e);if(b.width&&b.height){E=qa(b.width,b.height);ha(b.width+B,b.height+B)}break;
case 8:b=JSON.parse(e);if(f.onrequestcredential&&f.onrequestcredential(b))return;w.requestCredential(b);break;case 9:break;case 11:var p=function(){f.allowJoin(b.numericId,false);this.destroy()};var t=function(){f.allowJoin(b.numericId,true);this.destroy()};b=JSON.parse(e);if(f.onrequirejoin)g=f.onrequirejoin(b);if(g)break;n=__svi18n.info.title.applyArgs([b.name,b.numericId,b.__ip]);hi5.notifications.notify({"title":n,"msg":__svi18n.info.reqjoin,"cbYes":t,"cbNo":p})}}function Oa(a){var c=JSON.parse(a);
var d=c;sessionId=c.session;d.server=f.server;var b=hi5.$("joinSelect");if(b)b.value=d.joinMode;b=hi5.$("requestControl");if(b)b.disabled=d.hasControl;var e=z.page&&z.page.joinssh||"joinssh.html";e=location.protocol+"//"+location.host+"/"+e+"?id="+c.numericId;var g=c.webAddress;if(g&&g.length>0){var h=g.indexOf("://");var k=g.substring(h+3);h=k.indexOf("/");if(h>0)k=k.substring(0,h);if(k.toLowerCase()!=location.host.toLowerCase())e+="&gateway="+k}d.joinLink=e;f.sessionInfo.appInfo=d;if(c.ver&&c.ver!=
svGlobal.version)svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+c.ver);ja();if(f.onsessionstart)f.onsessionstart(f.sessionInfo)}function xb(a){var c=__svi18n.errorCode[a];if(!c)c="error "+a;if(f.onerror)f.onerror({name:a,message:c});if(f.displayMsg)hi5.notifications.notify({"msg":c});if(svGlobal.log>0)console.error(c)}function Ma(a){var c=JSON.parse(a);if(!c.name){if(svGlobal.log>0)console.erro("No error code for message:"+a);return}svGlobal.logger.info("msg="+a);if(f.onerror)f.onerror(c);
var d=__svi18n.errorCode["S"+c.name]||"";d+=c.message;f.showMessage(d)}function Ia(a){svGlobal.logger.info("opened...");y=true;l.send("87"+navigator.userAgent);if(f.onopen)f.onopen()}function Ua(a){svGlobal.logger.warn(a)}function da(a){svGlobal.logger.warn("closed ...");N.style.display="none";y=false;la=false;if(f&&f.onclose)f.onclose();try{if(J!=null){J.exit();J=null}if(w)w.close()}catch(c){}if(Q){Q.release();Q=null}h=null;Y=null;if(l){l.onopen=null;l.onmessage=null;l.onclose=null;l.onerror=null;
l=null}ka=null;w=null;if(E){E.release();E=null}if(f)f=null;if(window&&window.$ssh)window.$ssh=null;if(J!=null){J.exit();J=null}}function va(){if(e.fontSize<10)e.fontSize=10;if(e.fontSize<=12){k=e.fontSize+6;Z=2}else if(e.fontSize>=13&&e.fontSize<18){k=e.fontSize+8;Z=2}else if(e.fontSize>=19&&e.fontSize<25){k=e.fontSize+12;Z=3}else if(e.fontSize>=25){k=e.fontSize+16;Z=4}h.font=e.fontSize+"px Courier New";n=h.measureText("X").width;W=parseInt(p/k);C=parseInt(u/n);ga(parseInt(p/k))}function ja(){ta();
m=0;t=0;va();remotectrl.style.cursor="text";if(N==null){N=document.getElementById("cursorID");N.style.display="block";N.style.width=n+"px";N.style.height=k+"px"}la=true}function Wa(){var a=h.getImageData(0,0+(A-1)*k,C*n,(I-A)*k);h.fillStyle=G;h.fillRect(0,(A-1)*k,C*n,k);h.putImageData(a,0,A*k);h.fillStyle=F}function Xa(){var a=h.getImageData(0,A*k,C*n,(I-A)*k);h.fillStyle=G;h.fillRect(0,I*k-k,C*n,k);h.putImageData(a,0,(A-1)*k);h.fillStyle=F}function Ya(){}function Za(){var a=m/n/xa;a=a*1;a=parseInt(a)+
1;m=a*xa*n;if(m>=C*n){m=0;t+=k;ea("\n")}K()}function $a(){}function ab(){t+=k;ea("\n");ya()}function ya(){if(m>=C*n){m=0;t+=k}if(t>ba){for(;t>ba;)t-=k;K();if(sa){h.drawImage(Y,0,-k);h.fillStyle=G;h.fillRect(0,ba,u,k)}else{var a=h.getImageData(0,0+(A-0)*k,C*n,(I-A)*k);h.fillStyle=G;h.fillRect(0,(A-1)*k,C*n,(I-A+1)*k);h.putImageData(a,0,0+(A-1)*k)}h.fillStyle=F}}function ma(){m=m-n;if(m<0)m=0;K()}function bb(a){m+=a*n;K()}function cb(a){t+=a*k;ea("\n");K()}function db(a){m-=a*n;K()}function eb(a){t-=
a*k;K()}function fb(a,c){m=(c-1)*n;if(m<0)m=0;t=(a-1)*k;K()}function gb(a,c){ga(c,a)}function R(a){G=T[a]||e.bgColor||"black"}function S(a){F=T[a]||e.bgColor||"white";h.fillStyle=F}function hb(){h.fillStyle=G;h.fillRect(m,t,C*n-m,k);h.fillStyle=F}function ib(){h.fillStyle=G;h.fillRect(0,t,m,k);h.fillStyle=F}function jb(){h.fillStyle=G;h.fillRect(m,t,C*n-m,W*k-t);h.fillStyle=F}function ta(){h.fillStyle=G;h.fillRect(0,0,Y.width,Y.height);h.fillStyle=F}function K(){N.style.top=t+"px";N.style.left=m+
"px"}function yb(a,c,d){for(var b=c;b<d;)if(a.charCodeAt(b++)<32){b--;break}U(a.substring(c,b));return b}function kb(a){U(lb(a))}function U(a){na=a.length;h.fillStyle=G;h.fillRect(m,t,n*na,k);h.fillStyle=F;h.fillText(a,m,t+k-3*Z);m=m+na*n;ya();ea(a);K()}function lb(a){var c=a.getPosition();var d=0;var b=0;for(char2=0,char3=0,out="",end=a.getEnd(),bData=a.getData();c<end;){d=bData[c++];if(d>=32)switch(d>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:out+=String.fromCharCode(d);break;case 12:case 13:out+=
String.fromCharCode((d&31)<<6|bData[c++]&63);break;case 14:out+=String.fromCharCode((d&15)<<12|(bData[c++]&63)<<6|(bData[c++]&63)<<0)}else{if(d==13||d==27||d==8||d==9)c--;break}}a.setPosition(c);return out}function mb(a){var c=String.fromCharCode(a);O=O+c;if(L)U(c)}function zb(a,c,d){var b=c/k;if(a==0)nb[b]=d}function ob(){m=0;if(t>(I-1)*k)t=(I-1)*k;K()}function Ab(a){if(!f.openLink)return false;var c=a;a=a.toLowerCase();var d=a.indexOf("http://")==0||a.indexOf("https://")==0||a.indexOf("ftp://")==
0||a.indexOf("mailto:")==0||a.indexOf("tel:")==0||a.indexOf("callto:")==0;if(!d)if(a.indexOf("www.")==0){d=true;a="http://"+a}else if(a.indexOf("ftp.")==0){d=true;a="ftp://"+a}if(d){if(a.indexOf("\r")>0||a.indexOf("\n")>0)return false;if(f.onurlredirection&&f.onurlredirection(d))return true;w.processLink(c);return true}return false}function pb(a){if(!y)return;var c=a.getData("text/plain");if(c){c=c.replace(/\r\n/g,"\n");H(false,c,3);return true}return false}function qb(){if(!aa)return;aa.value=V;
var a=new hi5.Lightbox(document.getElementById("copydialog"));a.show();if(w)w.setIgnorePaste(false);setTimeout(function(){aa.scrollTop=aa.scrollHeight},10)}function ea(a,c){if(aa){V=V+a;if(V.length>1E5)V=V.substring(4E4)}if(f.onoutput)f.onoutput(a)}function rb(a){if(a==28){l.send((L?"5B":"5D")+O);O="";if(L)L=false;else{X=false;t+=k;m=0}}else if(a==14)if(O.length>0){O=O.substring(0,O.length-1);if(L){ma();U(" ");ma()}}}function H(a,c,d){if(L||X)rb(c);else l.send("8B"+d+"\t"+c);fa=c}function Da(a,c){var d=
0;var b=0;d=parseInt(a/n);b=parseInt(c/k);l.send("ED"+d+"\t"+b+"\t"+a+"\t"+c)}if(sessionStorage)sessionStorage.clear();var V="";this.displayMsg=true;this.reconnectTimes=0;this.openLink=true;this.setTitle=true;this.mode=0;var ia=typeof g=="object"?g:null;var za=typeof g=="object"||g.indexOf("/PLAY?")>0;if(za){this.mode=1;if(ia)g="";g+="&touchpad=on"}else if(g.indexOf("/JOIN?")>0){this.mode=2;this.reconnectOnResize=false}var z=hi5.appcfg||{img:{},toolbar:{fadable:true}};var e=hi5.tool.queryToObj(g.substring(g.indexOf("?")+
1));if(!e.color)e.color=32;var aa=ca(e["mapClipboard"])?document.getElementById("copytextarea"):null;this.server=e["server"];this.port=parseInt(e["port"],10);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:true,trueColor:true};var w=null;var y=false;var la=false;z.copyDialog=true;var B=0;var D=0;var v=new Array;var M=0;var m=0;var t=0;var n=0;var k=18;var Z=0;var T=["black","red","green","yellow","blue","magenta","cyan","white"];var F=e.fgColor||T[7];var G=e.bgColor||T[0];var xa=
8;var A=1;var I=24;var ba=0;var sa=true;var N=null;var W=0;var C=0;var na=0;var fa=0;var oa=false;var pa=false;var J=null;window.$ssh=this;var Q=new Ga(4194304);this.__que=Q;this.running=function(){return y};var f=this;var l=null;if(!u)u=window.innerWidth;u-=B;e.width=u;g+="&width="+u;if(!p)p=window.innerHeight;p-=B;e.height=p;g+="&height="+p;if(!e.fontSize){if(!P)P=13;e.fontSize=P;g+="&fontSize="+P}else e.fontSize=parseInt(e.fontSize,10);var E=qa(u,p);var h=E.getContext();var Y;var ka=new Ca;if(z.displayMsg!=
undefined)this.displayMsg=z.displayMsg;if(z.reconnectTimes!=undefined)this.reconnectTimes=z.reconnectTimes;if(z.openLink!=undefined)this.openLink=z.openLink;if(z.setTitle!=undefined)this.setTitle=z.setTitle;if(typeof z.useWSS=="boolean")g=(z.useWSS?"wss":"ws")+g.substring(g.indexOf("://"));this.getURL=function(){return g};var sb=parseInt(e.server_bpp||e.color||24);this.getColor=function(){return sb};this.setJoinMode=function(a){if(!y)return;l.send("8E1"+a)};this.refuseControl=function(a){if(!y)return;
l.send("8E3"+a)};this.giveControl=function(a){if(!y)return;l.send("8E4"+a)};this.requestControl=function(){if(!y)return;l.send("8E2")};this.play=function(){l.send("F3")};this.pause=function(){l.send("F2")};this.scan=function(a){l.send("F4"+(a?"1":"0"))};this.seek=function(a){if(w&&y){l.send("F4"+(a?"1":"0")+"\t"+(a/w.getScale()|0));E.pause(true)}};var L=false;var X=false;var O="";var wa=0;this.run=function(){Ha()};this.hide=function(){if(!w)return;if(document.getElementById("cursorID").style.display==
"block")document.getElementById("cursorID").style.display="none";w.hide()};this.showMessage=function(a){if(!f.displayMsg||!a)return;hi5.notifications.notify({"msg":a})};this.close=function(){if(l&&y)try{l.send("85");l.close()}catch(a){}else da()};if(!hi5.browser.isChromeApp)window.addEventListener("unload",da,false);else chrome.runtime.onSuspend.addListener(da);var tb=new ua(1024,function c(d){var b;for(var f=true;f;){b=d.getByte();if(b==undefined)break;switch(b){case 0:break;case 13:ob();break;case 27:b=
d.getByte();if(b==77){Wa();continue}if(b==68){Xa();continue}if(b==55){Ya();continue}if(b==40){b=d.getByte();if(b==66){b=d.getByte();if(b==27){b=d.getByte();if(b==41){b=d.getByte();if(b==48)continue;else d.skipBack(1)}else d.skipBack(1)}else d.skipBack(1)}else d.skipBack(1)}if(b!="0x5b")continue;D=0;v[D]=0;for(M=0;true;){b=d.getByte();if(b==59){if(M>0){D++;v[D]=0;M=0}continue}if(48<=b&&b<=57){v[D]=v[D]*10+(b-48);M++;continue}d.skipBack(1);break}b=d.getByte();if(b==109){if(M==0&&D==0){b=d.getByte();
if(b==15){S(7);R(0);continue}else{S(7);R(0);d.skipBack(1);continue}}for(var e=0;e<=D;e++)switch(v[e]){case 0:if(D==0){S(7);R(0)}else if(e==0)S(0);else R(0);break;case 1:break;case 2:break;case 4:break;case 5:case 8:break;case 7:if(D==0){S(7);R(0)}else if(e==0)S(7);else R(7);continue;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:S(v[e]-30);break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:R(v[e]-40);default:}continue}if(b==114){gb(v[0],v[1]);continue}if(b==72){if(M==
0&&D==0)v[0]=v[1]=1;fb(v[0],v[1]);continue}if(b==66){cb(v[0]);continue}if(b==68){db(v[0]);continue}if(b==67){if(M==0&&D==0)v[0]=1;bb(v[0]);continue}if(b==65){if(M==0&&D==0)v[0]=1;eb(v[0]);continue}if(b==63){b=d.getByte();if(b==49){b=d.getByte();if(b==108||b==104){b=d.getByte();if(b==27){b=d.getByte();if(b==">"||b=="=")continue}}else if(b==104){b=d.getByte();if(b==27){b=d.getByte();if(b==61)continue}}}else if(b==55){b=d.getByte();if(b==104)continue;else if(b==49)continue;d.skipBack(1);b=55}else;}if(b==
75){if(M==0&&D==0)hb();else ib();continue}if(b==74){jb();continue}break;case 7:break;case 9:Za();break;case 15:$a();break;case 8:ma();break;case 10:ab();break;default:d.skipBack(1);kb(d)}}});Q.setHandler(tb);var nb=new Array;this.addSurface=function(c){w=c;if(za)c.setPlayerMode();E.setContext(w.context);h=E.getContext();Y=h.canvas;c.forceTextArea=true;c.alwaysPaste=true;c.setAutoScale(f.mode>0);c.setSize(u+B,p+B);c.setController(ka);c.setFastCopy(ca(e["fastCopy"]));c.setTouchpad(ca(e["touchpad"]));
c.setClipboard(ca(e["mapClipboard"]));c.run(99997,false);c.onclipdata=pb};var ub=new Uint8Array(6);ub[0]=5;var vb=new Uint8Array(8);vb[0]=4;this.writeText=function(c){var d=0;for(var b=c.length;d<b;d++)H(false,c[d],3)};this.writeRawInput=function(c){if(!y)return;var d=parseInt(c.substring(0,2),16);var b=c.substring(2).split("\t");var e=0;var g=false;switch(d){case 128:var h=b[2];if(h==2)qb();return;case 129:return;case 130:return;case 131:H(true,b[2]==0?200:208,0);return;case 132:g=b[0]==0;e=parseInt(b[1]);
if(e==29)oa=g;if(e==56)pa=g;if(b[0]==0){if(e==69)return;H(g,e,0)}else if(e==42||e==54)H(false,e,2);else if(e==29)H(false,29,2);return;case 139:if(b[0]==0){if(oa&&pa)return;e=parseInt(b[1]);if(L||X){if(fa==29&&e==68)f.close();return}else{if(oa&&fa!=29)H(true,29,0);if(pa&&fa!=56)H(true,56,0);H(true,e,1)}}return;case 134:e=b[0].charCodeAt(0);if(L||X)mb(e);else if(e==47)H(true,191,1);else{if(e==160)b[0]=" ";H(false,b[0],3)}return}svGlobal.logger.warn("Unknowncode: "+b[1]+" type:"+d)}};
